{{- $cfg_ext := tpl .Values.hclCache.configMap.cache_cfg_ext . | fromYaml}}
{{- if and .Values.ingress.enabled (ne .Values.ingress.ingressController "ambassador") (ne .Values.ingress.ingressController "emissary") (.Values.cacheApp.enabled) (.Values.openshiftDeployment.enabled) ($cfg_ext.redis.enabled) -}}
{{- $envTypeList := splitList "," (nospace .Values.common.environmentType) -}}
{{- range $envType := $envTypeList -}}
{{- if ne $envType "share" }}
{{- $ingress_conf := $.Values.ingress.cache.auth }}
{{- if eq $envType "live" }}
{{ $ingress_conf = $.Values.ingress.cache.live }}
{{- end }}
{{- if $ingress_conf.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}-cache-route
  namespace: {{ $.Release.Namespace }}
  labels:
    app: HCL-Commerce
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "-" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    group: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}
spec:
  host: {{ tpl ($ingress_conf.domain | toString) $ }}
  to:
    kind: Service
    name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}cache-app
  port:
    targetPort: 40901
  tls:
    termination: reencrypt
    destinationCACertificate: |-
{{ $.Values.openshiftDeployment.destinationCACertificate | indent 6 }}
{{- end }}
{{- end }}
---
{{- end }}
{{- end }}