{{- range $ingress_controller := list "gke" "nginx" -}}
{{- if eq (include "hcl-commerce.hasIngressController" (list $ingress_controller $)) "true" -}}
{{- $ingress_name_suffix := "gke" -}}{{- if eq $ingress_controller "nginx" -}}{{- $ingress_name_suffix = "community-nginx" -}}{{- end -}}
{{- if and $.Values.ingress.enabled $ingress_controller -}}
{{- $envTypeList := splitList "," (nospace $.Values.common.environmentType) -}}
{{- range $envType := $envTypeList -}}
{{- if ne $envType "share" }}
{{- $ingress_conf := $.Values.ingress.cmc.auth }}
{{- if eq $envType "live" }}
{{ $ingress_conf = $.Values.ingress.cmc.live }}
{{- end }}
{{- if or (eq $.Values.common.searchEngine "solr") (not $.Values.storeWeb.enabled) (and (eq $envType "auth") (ne $ingress_conf.domain $.Values.ingress.reactstore.auth.domain)) (and (eq $envType "live") (ne $ingress_conf.domain $.Values.ingress.reactstore.live.domain)) }}
apiVersion: {{ $.Values.ingress.apiVersion }}
kind: Ingress
metadata:
  name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}-cmc-{{ $ingress_name_suffix }}-ingress
  namespace: {{ $.Release.Namespace }}
  annotations:
    ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    {{- if eq $ingress_controller "nginx" }}
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.org/ssl-services: "{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}ts-web,{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}tooling-web"
    {{- end }}
    {{- if eq $ingress_controller "gke" }}
    {{- if $.Values.ingress.cmc.gkeCustomAnnotations }}
{{ toYaml $.Values.ingress.cmc.gkeCustomAnnotations | indent 4 }}
    {{- end }}
    {{- else }}
    {{- if $.Values.ingress.cmc.communityNginxCustomAnnotations }}
{{ toYaml $.Values.ingress.cmc.communityNginxCustomAnnotations | indent 4 }}
    {{- end }}
    {{- end }}
  labels:
    app: HCL-Commerce
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "-" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    group: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}
spec:
  {{- if eq $ingress_controller "nginx" }}
  ingressClassName: {{ default "nginx" $ingress_conf.communityNginxClass | quote }}
  {{- else if eq $ingress_controller "gke" }}
  ingressClassName: {{ default "gce" $ingress_conf.gkeClass | quote }}
  {{- end }}
  tls:
  - hosts:
    - {{ tpl ($ingress_conf.domain | toString) $ }}
    secretName: {{ default (printf "%s%s%s-certificate" $.Values.common.tenant $.Values.common.environmentName $envType) ($ingress_conf.tlsSecret) }}
  rules:
  - host: {{ tpl ($ingress_conf.domain | toString) $ }}
    http:
      paths:
      {{- if eq $.Values.ingress.apiVersion "networking.k8s.io/v1beta1" }}
      - path: {{- if eq $ingress_controller "nginx" }} / {{- else if eq $ingress_controller "gke" }} /* {{- end }}
        backend:
          serviceName: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}ts-web
          servicePort: 8000
      - path: {{- if eq $ingress_controller "nginx" }} /tooling {{- else if eq $ingress_controller "gke" }} /tooling/* {{- end }}
        backend:
          serviceName: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}tooling-web
          servicePort: 7443
      {{- if $.Values.common.localStoreEnabled }}
      - path: {{- if eq $ingress_controller "nginx" }} /webapp/ {{- else if eq $ingress_controller "gke" }} /webapp/* {{- end }}
        backend:
          serviceName: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}ts-web
          servicePort: 8443
      - path: {{- if eq $ingress_controller "nginx" }} /wcsstore/ {{- else if eq $ingress_controller "gke" }} /wcsstore/* {{- end }}
        backend:
          serviceName: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}ts-web
          servicePort: 8443
      {{- end }}
      {{- if $.Values.approvalApp.enabled }}
      - path: {{- if eq $ingress_controller "nginx" }} /approvals {{- else if eq $ingress_controller "gke" }} /approvals/* {{- end }}
        backend:
          serviceName: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}approval-app
          servicePort: 6643
      {{- if $.Values.ingress.enableManageApprovalPage }}
      - path: /approvals/manage-approval
        backend:
          serviceName: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}ts-web
          servicePort: 8000
      {{- if eq $ingress_controller "gke" }}
      - path: /approvals/manage-approval/*
        backend:
          serviceName: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}ts-web
          servicePort: 8000
      {{- end }}
      {{- end }}
      {{- end }}
      {{- else if eq $.Values.ingress.apiVersion "networking.k8s.io/v1" }}
      - path: {{- if eq $ingress_controller "nginx" }} / {{- else if eq $ingress_controller "gke" }} /* {{- end }}
        pathType: {{- if eq $ingress_controller "nginx" }} Prefix {{- else if eq $ingress_controller "gke" }} ImplementationSpecific {{- end }}
        backend:
          service:
            name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}ts-web
            port:
              number: 8000
      - path: {{- if eq $ingress_controller "nginx" }} /tooling {{- else if eq $ingress_controller "gke" }} /tooling/* {{- end }}
        pathType: {{- if eq $ingress_controller "nginx" }} Prefix {{- else if eq $ingress_controller "gke" }} ImplementationSpecific {{- end }}
        backend:
          service:
            name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}tooling-web
            port:
              number: 7443
      {{- if $.Values.common.localStoreEnabled }}
      - path: {{- if eq $ingress_controller "nginx" }} /webapp/ {{- else if eq $ingress_controller "gke" }} /webapp/* {{- end }}
        pathType: {{- if eq $ingress_controller "nginx" }} Prefix {{- else if eq $ingress_controller "gke" }} ImplementationSpecific {{- end }}
        backend:
          service:
            name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}ts-web
            port:
              number: 8443
      - path: {{- if eq $ingress_controller "nginx" }} /wcsstore/ {{- else if eq $ingress_controller "gke" }} /wcsstore/* {{- end }}
        pathType: {{- if eq $ingress_controller "nginx" }} Prefix {{- else if eq $ingress_controller "gke" }} ImplementationSpecific {{- end }}
        backend:
          service:
            name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}ts-web
            port:
              number: 8443
      {{- end }}
      {{- if $.Values.approvalApp.enabled }}
      - path: {{- if eq $ingress_controller "nginx" }} /approvals {{- else if eq $ingress_controller "gke" }} /approvals/* {{- end }}
        pathType: {{- if eq $ingress_controller "nginx" }} Prefix {{- else if eq $ingress_controller "gke" }} ImplementationSpecific {{- end }}
        backend:
          service:
            name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}approval-app
            port:
              number: 6643
      {{- if $.Values.ingress.enableManageApprovalPage }}
      - path: /approvals/manage-approval
        pathType: {{- if eq $ingress_controller "nginx" }} Prefix {{- else if eq $ingress_controller "gke" }} ImplementationSpecific {{- end }}
        backend:
          service:
            name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}ts-web
            port:
              number: 8000
      {{- if eq $ingress_controller "gke" }}
      - path: /approvals/manage-approval/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}ts-web
            port:
              number: 8000
      {{- end }}
      {{- end }}
      {{- end }}
      {{- end }}
{{- end }}
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}