{{- if and ($.Values.ingress.enabled) (eq $.Values.common.searchEngine "elastic") (eq (include "hcl-commerce.hasIngressController" (list "f5-nginx" .)) "true") -}}
{{- $envTypeList := splitList "," (nospace .Values.common.environmentType) -}}
{{- if has "share" $envTypeList }}
{{- $ingress_conf := $.Values.ingress.ingest }}
apiVersion: {{ $.Values.ingress.apiVersion }}
kind: Ingress
metadata:
  name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}ingest-f5-nginx-ingress
  namespace: {{ $.Release.Namespace }}
  annotations:
    nginx.org/proxy-buffer-size: "256k"
    nginx.org/proxy-buffers: "16 512k"
    nginx.org/proxy-busy-buffers-size: "512k"
    {{- if $.Values.ingress.ingest.f5NginxCustomAnnotations }}
{{ toYaml $.Values.ingress.ingest.f5NginxCustomAnnotations | indent 4 }}
    {{- end }}
  labels:
    app: HCL-Commerce
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "-" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    group: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}
spec:
  ingressClassName: {{ default "f5-nginx" $ingress_conf.f5NginxClass | quote }}
  tls:
  - hosts:
    - {{ tpl ($ingress_conf.domain | toString) $ }}
    secretName: {{ default (printf "%s%sshare-certificate" $.Values.common.tenant $.Values.common.environmentName) ($ingress_conf.tlsSecret) }}
  rules:
  - host: {{ tpl ($ingress_conf.domain | toString) $ }}
    http:
      paths:
      {{- if eq $.Values.ingress.apiVersion "networking.k8s.io/v1beta1" }}
      - path: /
        backend:
          serviceName: {{ .Values.common.tenant }}{{ .Values.common.environmentName }}{{.Values.ingestApp.name}}
          servicePort: 30800
      {{- else if eq $.Values.ingress.apiVersion "networking.k8s.io/v1" }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.common.tenant }}{{ .Values.common.environmentName }}{{.Values.ingestApp.name}}
            port:
              number: 30800
      {{- end }}
{{- end }}
{{- end }}
---
