{{- if and .Values.ingress.enabled (eq .Values.ingress.ingressController "emissary") (eq $.Values.common.searchEngine "elastic") (.Values.ingress.nifi.enabled) -}}
{{- $envTypeList := splitList "," (nospace .Values.common.environmentType) -}}
{{- if has "share" $envTypeList }}
{{- $ingress_conf := $.Values.ingress.nifi }}
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: commerce-nifi-host
spec:
  {{- if or $.Values.global.emissaryID $ingress_conf.ingressClass }}
  ambassador_id: [ '{{ default $.Values.global.emissaryID $ingress_conf.ingressClass }}' ]
  {{- end }}
  hostname: {{ tpl ($ingress_conf.domain | toString) $ }}
  acmeProvider:
    authority: none
  tlsSecret:
    name: {{ default (printf "%s%sshare-certificate" $.Values.common.tenant $.Values.common.environmentName) ($ingress_conf.tlsSecret) }}
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: commerce-nifi-mapping
spec:
  {{- if or $.Values.global.emissaryID $ingress_conf.ingressClass }}
  ambassador_id: [ '{{ default $.Values.global.emissaryID $ingress_conf.ingressClass }}' ]
  {{- end }}
  prefix: /
  hostname: {{ tpl ($ingress_conf.domain | toString) $ }}
  host_regex: false
  case_sensitive: false
  timeout_ms: 10000
  service: http://{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}nifi-app:30600
  bypass_auth: true
---
{{- end }}
{{- end }}