{{- if eq .Values.common.searchEngine "elastic" -}}
{{- $envTypeList := splitList "," (nospace .Values.common.environmentType) -}}
{{- range $envType := $envTypeList -}}
{{- if ne $envType "share" -}}
{{- $_ := set $ "envType" $envType }}
######################################################
# Licensed Materials - Property of HCL Technologies
#  HCL Commerce
#  (C) Copyright HCL Technologies Limited 1996, 2020
######################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: HCL-Commerce
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "-" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    app.kubernetes.io/name: {{ include "name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
  name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}{{$.Values.queryApp.name}}
  namespace: {{ $.Release.Namespace }}
spec:
  selector: 
    matchLabels:
      chart: {{ $.Chart.Name }}
      release: {{ $.Release.Name }}
      heritage: {{ $.Release.Service }}
      component: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}{{$.Values.queryApp.name}}
      group: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}
  replicas: {{ get $.Values.queryApp.replica $envType }}
  template:
    metadata:
      annotations:
        productName: "HCL Commerce"
        productVersion: {{ $.Values.common.productVersion | quote }}
        {{- if and ($.Values.metrics.enabled) ($.Values.metrics.prometheusAnnotations.enabled) }}
        prometheus.io/scrape: "true"
        prometheus.io/path: /monitor/metrics
        prometheus.io/port: "30280"
        {{- end }}
      labels:
        app: HCL-Commerce
        chart: {{ $.Chart.Name }}
        release: {{ $.Release.Name }}
        heritage: {{ $.Release.Service }}
        component: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}{{$.Values.queryApp.name}}
        group: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}
        app.kubernetes.io/name: {{ include "name" $ }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
    spec:
      {{- if $.Values.queryApp.nodeSelector }}
      nodeSelector:
{{ get $.Values.queryApp.nodeSelector $envType | toYaml | indent 8 }}
      {{- end }}
      affinity:
        nodeAffinity:
           {{- if $.Values.queryApp.nodeLabel }}
           requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: wc-node-select-flag
                  operator: In
                  values: 
                  - {{ $.Values.queryApp.nodeLabel }}
           {{- else }}
           requiredDuringSchedulingIgnoredDuringExecution:
           {{- include "nodeAffinityRequiredDuringScheduling" $ | indent 8 }}
           {{- end }}   
           preferredDuringSchedulingIgnoredDuringExecution:
           {{- include "nodeAffinityPreferredDuringScheduling" $ | indent 8 }}
      {{- include "queryapp-podAntiAffinity" $ | indent 6 }}   
      hostNetwork: false
      hostPID: false
      hostIPC: false
      serviceAccountName: {{ $.Values.common.serviceAccountName | default (printf "%s-commerce" $.Release.Name) }}
      initContainers:
      {{- if and (not $.Values.global.sofySandboxContext) ($.Values.queryApp.userScripts.enabled) }}
      - name: user-script-transfer
        image: "{{ include "image.repo" $ }}{{ $.Values.queryApp.userScripts.initContainer.image }}:{{ $.Values.queryApp.userScripts.initContainer.tag }}"
        {{- if $.Values.common.imagePullPolicy }}
        imagePullPolicy: {{ $.Values.common.imagePullPolicy }}
        {{- end }}
        command: 
{{ toYaml $.Values.queryApp.userScripts.initContainer.command | indent 10 }}
        args:
{{ toYaml $.Values.queryApp.userScripts.initContainer.args | indent 10 }}
        {{- if $.Values.queryApp.userScripts.initContainer.env }}
        env:
          {{- range $key, $value := $.Values.queryApp.userScripts.initContainer.env }}
          - name: {{ $key | quote}}
            value: {{ $value | quote}}
          {{- end }}
        {{- end }}
        volumeMounts:
          - name:  user-scripts
            mountPath: /data
      {{- end }}
      {{- if and $.Values.global.sofySandboxContext $.Values.queryApp.demoPack.enabled }}
      - name: demo-pack-transfer
        image: "{{ $.Values.global.hclPreviewImageRegistry }}/{{ $.Values.queryApp.demoPack.initContainer.image }}:{{ $.Values.queryApp.demoPack.initContainer.tag }}"
        {{- if $.Values.common.imagePullPolicy }}
        imagePullPolicy: {{ $.Values.common.imagePullPolicy }}
        {{- end }}
        command: 
{{ toYaml $.Values.queryApp.demoPack.initContainer.command | indent 10 }}
        args:
{{ toYaml $.Values.queryApp.demoPack.initContainer.args | indent 10 }}
        {{- if $.Values.queryApp.demoPack.initContainer.env }}
        env:
          {{- range $key, $value := $.Values.queryApp.demoPack.initContainer.env }}
          - name: {{ $key | quote}}
            value: {{ $value | quote}}
          {{- end }}
        {{- end }}
        volumeMounts:
          - name:  demopack
            mountPath: /data
      {{- end }}
      - name: query-dependence-check
        image: "{{ include "image.repo" $ }}{{ $.Values.supportC.image }}:{{ $.Values.supportC.tag }}"
        {{- if $.Values.common.imagePullPolicy }}
        imagePullPolicy: {{ $.Values.common.imagePullPolicy }}
        tty: true
        {{- end }}
        args: ['depcheck', '-component','query','-tenant',{{ $.Values.common.tenant }},'-env',{{ $.Values.common.environmentName}},'-envtype',{{ $envType }},'-namespace',{{ $.Release.Namespace }},'-interval_time','20','-expect_during_time','600','-timeout','10','-spiuser_pwd_encrypte',{{ $.Values.common.spiUserPwdBase64 }}]
      volumes:
        - name: logs-sharing
          emptyDir: {}
        - name: cores-sharing
        {{- if get $.Values.queryApp.coresSharingPersistentVolumeClaim $envType }}
          persistentVolumeClaim:
            claimName: {{ get $.Values.queryApp.coresSharingPersistentVolumeClaim $envType }}
        {{- else }}
          emptyDir: {}
        {{- end }}
      {{- if $.Values.common.bindingConfigMap }}
        - name: config-volume
          configMap:
            name: {{ $.Values.common.bindingConfigMap }} 
      {{- end }}
      {{- if $.Values.hclCache.configMap }}
        - name: hcl-cache-config
          configMap:
            name: {{ include "hcl.cache.configmap.name" $ | quote }}
      {{- end }}
      {{- if and (not $.Values.global.sofySandboxContext) ($.Values.queryApp.userScripts.enabled) }}
        - name: user-scripts
          emptyDir: {}
      {{- end }}
      {{- if and $.Values.global.sofySandboxContext $.Values.queryApp.demoPack.enabled }}
        - name: demopack
          emptyDir: {}
      {{- end }}
      {{- if include "image.pull.secret" $ }}
      imagePullSecrets:
        - name: {{ include "image.pull.secret" $ }}
      {{- end }}
      containers:
      - name: query-app
        image: "{{ include "image.repo" $ }}{{ $.Values.queryApp.image }}:{{ $.Values.queryApp.tag }}"
        {{- if $.Values.common.imagePullPolicy }}
        imagePullPolicy: {{ $.Values.common.imagePullPolicy }}
        {{- end }}
        resources:
{{ get $.Values.queryApp.resources $envType | toYaml | indent 12 }}
        env:
        - name: "LICENSE"
          value: {{ $.Values.license | quote }}
        - name: "CONFIGURE_MODE"
          value: {{ $.Values.common.configureMode | quote }}
        - name: "ENVIRONMENT"
          value: {{ $.Values.common.environmentName | quote }}
        - name: "TENANT"
          value: {{ $.Values.common.tenant | quote }}
        - name: "ENVTYPE"
          value: {{ $envType | quote }}
        {{- if $.Values.common.timezone }}
        - name: "TZ"
          value: {{ $.Values.common.timezone | quote }}
        {{- end }}
        {{- if $.Values.logging.jsonLogging.enabled }}
        - name: "ENABLE_JSON_LOGGING"
          value: "true"
        {{- end }}
        - name: "DOMAIN_NAME"
          value: "{{ $.Release.Namespace }}.svc.cluster.local"
        {{- if $.Values.metrics.enabled }}
        - name: "EXPOSE_METRICS"
          value: "true"
        {{- end }}
        - name: "VAULT_CA"
          value: {{ $.Values.vaultCA.enabled | quote }}
        {{- if (or (eq $.Values.common.configureMode "Vault") $.Values.vaultCA.enabled) }}
        - name: "VAULT_URL"
          value: {{ $.Values.common.vaultUrl | quote  }}
        {{- if $.Values.common.vaultTokenSecret }}
        - name: "VAULT_TOKEN"
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.common.vaultTokenSecret }}
              key: VAULT_TOKEN
        {{- end }}
        {{- end }}
        {{- if and (eq $envType "auth") $.Values.global.sofySolutionContext }}
        - name: "EXTERNAL_DOMAIN_NAME"
        {{- if $.Values.global.domain }}
          value: {{ $.Values.global.domain }}
        {{- else }}
          valueFrom:
              configMapKeyRef:
                name: {{ $.Release.Name }}-domain
                key: HOST
        {{- end }}
        - name: "TOOLING_ORIGIN"
          value: "https://commerce-preview.$(EXTERNAL_DOMAIN_NAME)"
        {{- else }} # non sofy deployment
        - name: "TOOLING_ORIGIN"
          value: "https://{{ tpl ($.Values.ingress.cmc.auth.domain | toString) $ }}"
        {{- end}}
        {{- if $.Values.common.ipv6Enabled }}
        - name: "IPV6_ENABLED"
          value: "true"
        {{- end }}
{{- if get $.Values.queryApp.envParameters $envType }}
     {{- range $key, $value := get $.Values.queryApp.envParameters $envType }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
     {{- end }} 
{{- end }}
        ports: 
        - containerPort: 30900
          name: port30900
          protocol: TCP
        - containerPort: 30901
          name: port30901
          protocol: TCP
        startupProbe:
          httpGet:
            path: /search/resources/health
            port: 30901
            scheme: HTTPS
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 48
        readinessProbe:
          httpGet:
            path: /search/resources/health
            port: 30901
            scheme: HTTPS
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /search/resources/health
            port: 30901
            scheme: HTTPS
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 15
        securityContext:
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            runAsUser: 0
            privileged: false
            capabilities:
              drop:
              - all
              add:
              - CHOWN
              - DAC_OVERRIDE
              - FOWNER
              - FSETID
              - KILL
              - SETGID
              - SETUID
              - SETPCAP
              - NET_BIND_SERVICE
              - NET_RAW
              - SYS_CHROOT
              - MKNOD
              - AUDIT_WRITE
              - SETFCAP
        volumeMounts:
          - name: logs-sharing
            mountPath: /opt/WebSphere/Liberty/usr/servers/default/logs/container
          - name: cores-sharing
            mountPath: /opt/WebSphere/Liberty/usr/servers/default/cores/container
        {{- if $.Values.common.bindingConfigMap }}
          - name: config-volume
            mountPath: /SETUP/ext-config/config.properties
            subPath: config.properties
            readOnly: false
        {{- end }}
        {{- if $.Values.hclCache.configMap }}
          - name: hcl-cache-config
            mountPath: /SETUP/hcl-cache/cache_cfg-ext.yaml
            subPath: cache_cfg-ext.yaml
          - name: hcl-cache-config
            mountPath: /SETUP/hcl-cache/redis_cfg.yaml
            subPath: redis_cfg.yaml
        {{- end }}
        {{- if and (not $.Values.global.sofySandboxContext) ($.Values.queryApp.userScripts.enabled) }}
          - name:  user-scripts
            mountPath: /SETUP/user_scripts
        {{- end }}
        {{- if and $.Values.global.sofySandboxContext $.Values.queryApp.demoPack.enabled }}
          - name:  demopack
            mountPath: /SETUP/user_scripts
        {{- end }}
{{- end }}
---
{{- end }}
{{- end }}