{{- $envTypeList := splitList "," (nospace .Values.common.environmentType) -}}
{{- if and (has "live" $envTypeList) (eq .Values.common.searchEngine "solr") (not .Values.searchAppSlave.persistence.enabled) }}
{{- $_ := set $ "envType" "live" }}
######################################################
# Licensed Materials - Property of HCL Technologies
#  HCL Commerce
#  (C) Copyright HCL Technologies Limited 1996, 2020
######################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}live{{$.Values.searchAppSlave.name}}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: HCL-Commerce
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "-" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    app.kubernetes.io/name: {{ include "name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  selector:
    matchLabels:
      {{- if $.Values.backwardCompatibility.selector.app }}
      app: {{ $.Values.backwardCompatibility.selector.app }}
      {{- end }}
      {{- if $.Values.backwardCompatibility.selector.chart }}
      chart: {{ $.Values.backwardCompatibility.selector.chart }}
      {{- else }}
      chart: {{ $.Chart.Name }}
      {{- end }}
      release: {{ $.Release.Name }}
      component: {{ $.Values.common.tenant }}{{$.Values.common.environmentName}}live{{$.Values.searchAppSlave.name}}
      group: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}live
      {{- range $key, $value := $.Values.backwardCompatibility.selector.extraSelector }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
  replicas: {{ $.Values.searchAppSlave.replica }}
  template:
    metadata:
      annotations:
        productName: "HCL Commerce"
        productVersion: {{ $.Values.common.productVersion | quote }}
        {{- if and ($.Values.metrics.enabled) ($.Values.metrics.prometheusAnnotations.enabled) }}
        prometheus.io/scrape: "true"
        prometheus.io/path: /monitor/metrics
        prometheus.io/port: "3280"
        {{- end }}
      labels:
        {{- if $.Values.backwardCompatibility.selector.app }}
        app: {{ $.Values.backwardCompatibility.selector.app }}
        {{- else }}
        app: HCL-Commerce
        {{- end }}
        {{- if $.Values.backwardCompatibility.selector.chart }}
        chart: {{ $.Values.backwardCompatibility.selector.chart }}
        {{- else }}
        chart: {{ $.Chart.Name }}
        {{- end }}
        release: {{ $.Release.Name }}
        component: {{ $.Values.common.tenant }}{{$.Values.common.environmentName}}live{{$.Values.searchAppSlave.name}}
        group: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}live
        app.kubernetes.io/name: {{ include "name" $ }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
        {{- range $key, $value := $.Values.backwardCompatibility.selector.extraSelector }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      {{- if $.Values.searchAppSlave.nodeSelector }}
      nodeSelector:
{{ toYaml $.Values.searchAppSlave.nodeSelector | indent 8 }}
      {{- end }}
      affinity:
        nodeAffinity:
           {{- if $.Values.searchAppSlave.nodeLabel }}
           requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: wc-node-select-flag
                  operator: In
                  values:
                  - {{ $.Values.searchAppSlave.nodeLabel }}
           {{- else }}
           requiredDuringSchedulingIgnoredDuringExecution:
           {{- include "nodeAffinityRequiredDuringScheduling" . | indent 8 }}
           {{- end }}
           preferredDuringSchedulingIgnoredDuringExecution:
           {{- include "nodeAffinityPreferredDuringScheduling" . | indent 8 }}
      {{- include "searchapp-podAntiAffinity" . | indent 6 }}
      hostNetwork: false
      hostPID: false
      hostIPC: false
      serviceAccountName: {{ $.Values.common.serviceAccountName | default (printf "%s-commerce" $.Release.Name) }}
      securityContext:
        fsGroup: 1000
      initContainers:
      {{- if and (not $.Values.global.sofySandboxContext) ($.Values.searchAppSlave.userScripts.enabled) }}
      - name: user-script-transfer
        image: "{{ include "image.repo" $ }}{{ $.Values.searchAppSlave.userScripts.initContainer.image }}:{{ $.Values.searchAppSlave.userScripts.initContainer.tag }}"
        {{- if $.Values.common.imagePullPolicy }}
        imagePullPolicy: {{ $.Values.common.imagePullPolicy }}
        {{- end }}
        command: 
{{ toYaml $.Values.searchAppSlave.userScripts.initContainer.command | indent 10 }}
        args:
{{ toYaml $.Values.searchAppSlave.userScripts.initContainer.args | indent 10 }}
        {{- if $.Values.searchAppSlave.userScripts.initContainer.env }}
        env:
          {{- range $key, $value := $.Values.searchAppSlave.userScripts.initContainer.env }}
          - name: {{ $key | quote}}
            value: {{ $value | quote}}
          {{- end }}
        {{- end }}
        volumeMounts:
          - name:  user-scripts
            mountPath: /data
      {{- end }}
      {{- if and $.Values.global.sofySandboxContext $.Values.searchAppSlave.demoPack.enabled }}
      - name: demo-pack-transfer
        image: "{{ $.Values.global.hclPreviewImageRegistry }}/{{ $.Values.searchAppSlave.demoPack.initContainer.image }}:{{ $.Values.searchAppSlave.demoPack.initContainer.tag }}"
        {{- if $.Values.common.imagePullPolicy }}
        imagePullPolicy: {{ $.Values.common.imagePullPolicy }}
        {{- end }}
        command: 
{{ toYaml $.Values.searchAppSlave.demoPack.initContainer.command | indent 10 }}
        args:
{{ toYaml $.Values.searchAppSlave.demoPack.initContainer.args | indent 10 }}
        {{- if $.Values.searchAppSlave.demoPack.initContainer.env }}
        env:
          {{- range $key, $value := $.Values.searchAppSlave.demoPack.initContainer.env }}
          - name: {{ $key | quote}}
            value: {{ $value | quote}}
          {{- end }}
        {{- end }}
        volumeMounts:
          - name:  demopack
            mountPath: /data
      {{- end }}
      - name: search-dependence-check
        image: "{{ include "image.repo" . }}{{ $.Values.supportC.image }}:{{ $.Values.supportC.tag }}"
        tty: true
        {{- if $.Values.common.imagePullPolicy }}
        imagePullPolicy: {{ $.Values.common.imagePullPolicy }}
        {{- end }}
        args: ['depcheck', '-component','search','-tenant',{{ $.Values.common.tenant }},'-env',{{ $.Values.common.environmentName}},'-envtype',live,'-namespace',{{ $.Release.Namespace }},'-interval_time','20','-expect_during_time','600','-timeout','5','-spiuser_pwd_encrypte',{{ $.Values.common.spiUserPwdBase64 }}]
      volumes:
        - name: logs-sharing
          emptyDir: {}
        - name: cores-sharing
        {{- if $.Values.searchAppSlave.coresSharingPersistentVolumeClaim }}
          persistentVolumeClaim:
            claimName: {{ $.Values.searchAppSlave.coresSharingPersistentVolumeClaim }}
        {{- else }}
          emptyDir: {}
        {{- end }}
      {{- if $.Values.common.bindingConfigMap }}
        - name: config-volume
          configMap:
            name: {{ $.Values.common.bindingConfigMap }}
      {{- end }}
      {{- if $.Values.hclCache.configMap }}
        - name: hcl-cache-config
          configMap:
            name: {{ include "hcl.cache.configmap.name" $ | quote }}
      {{- end }}
      {{- if and (not $.Values.global.sofySandboxContext) ($.Values.searchAppSlave.userScripts.enabled) }}
        - name: user-scripts
          emptyDir: {}
      {{- end }}
      {{- if and $.Values.global.sofySandboxContext $.Values.searchAppSlave.demoPack.enabled }}
        - name: demopack
          emptyDir: {}
      {{- end }}
      {{- if include "image.pull.secret" . }}
      imagePullSecrets:
        - name: {{ include "image.pull.secret" . }}
      {{- end }}
      containers:
      - name: search-app-slave
        image: "{{ include "image.repo" . }}{{$.Values.searchAppSlave.image}}:{{ $.Values.searchAppSlave.tag }}"
        {{- if $.Values.common.imagePullPolicy }}
        imagePullPolicy: {{ $.Values.common.imagePullPolicy }}
        {{- end }}
        resources:
{{ toYaml $.Values.searchAppSlave.resources | indent 12 }}
        env:
        - name: "LICENSE"
          value: {{ $.Values.license | quote }}
        {{- if $.Values.common.commerceVersion }}
        {{- if (or (eq $.Values.common.commerceVersion "9.0.0.1") (eq $.Values.common.commerceVersion "9.0.0.0")) }}
          {{- if $.Values.common.overridePreconfig }}
        - name: "OVERRIDE_PRECONFIG"
          value: {{ $.Values.common.overridePreconfig | quote }}
          {{- end }}
        {{- end}}
        {{- else }}
        - name: "CONFIGURE_MODE"
          value: {{ $.Values.common.configureMode | quote }}
        {{- end }}
        {{- if $.Values.common.timezone }}
        - name: "TZ"
          value: {{ $.Values.common.timezone | quote }}
        {{- end }}
        - name: "ENVIRONMENT"
          value: {{ $.Values.common.environmentName | quote }}
        - name: "TENANT"
          value: {{$.Values.common.tenant | quote}}
        - name: "ENVTYPE"
          value: "live"
        {{- if $.Values.logging.jsonLogging.enabled }}
        - name: "ENABLE_JSON_LOGGING"
          value: "true"
        {{- end }}
        - name: "DOMAIN_NAME"
          value: "{{ $.Release.Namespace }}.svc.cluster.local"
        - name: "DBTYPE"
          value: {{ $.Values.common.dbType | quote }}
        - name: "VAULT_CA"
          value: {{ $.Values.vaultCA.enabled | quote }}
        - name: "WORKAREA"
          value: "/search"
        - name: "SOLR_MASTER"
          value: "false"
        - name: "SOLR_SLAVE"
          value: "true"
        - name: "SOLR_MASTER_SERVER_URL"
          value: "{{ $.Values.common.tenant }}{{$.Values.common.environmentName}}livesearch-app-repeater.{{ $.Release.Namespace }}.svc.cluster.local:3738"
        - name: "SOLR_REPLICATION_POLLINTERVAL"
          value: "00:00:60"
        - name: "SPIUSER_NAME"
          value: {{ $.Values.common.spiUserName | quote }}
        - name: "SPIUSER_PWD"
          value: {{ $.Values.common.spiUserPwdAes | quote }}
        {{- if $.Values.metrics.enabled }}
        - name: "EXPOSE_METRICS"
          value: "true"
        {{- end }}
        {{- if (or (eq $.Values.common.configureMode "Vault") $.Values.vaultCA.enabled) }}
        - name: "VAULT_URL"
          value: {{ $.Values.common.vaultUrl | quote }}
        {{- if $.Values.common.vaultTokenSecret }}
        - name: "VAULT_TOKEN"
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.common.vaultTokenSecret }}
              key: VAULT_TOKEN
        {{- end }}
        {{- end }}
        {{- if $.Values.common.ipv6Enabled }}
        - name: "IPV6_ENABLED"
          value: "true"
        {{- end }}
{{- if $.Values.searchAppSlave.envParameters }}
     {{- range $key, $value := $.Values.searchAppSlave.envParameters }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
     {{- end }}
{{- end }}
        ports:
        - containerPort: 3737
          name: port3737
        - containerPort: 3738
          name: port3738
          protocol: TCP
        startupProbe:
          httpGet:
            path: /search/admin/resources/health/status?type=container&mode=startup
            port: 3738
            scheme: HTTPS
            httpHeaders:
            - name: Authorization
              value: Basic {{ $.Values.common.spiUserPwdBase64 }}
          failureThreshold: 90
          periodSeconds: 10
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /search/admin/resources/health/status?type=container&mode=readiness
            port: 3738
            scheme: HTTPS
            httpHeaders:
            - name: Authorization
              value: Basic {{ $.Values.common.spiUserPwdBase64 }}
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /search/admin/resources/health/ping
            port: 3738
            scheme: HTTPS
            httpHeaders:
            - name: Authorization
              value: Basic {{ $.Values.common.spiUserPwdBase64 }}
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 15
        securityContext:
            {{- if $.Values.common.runAsNonRoot.enabled }}
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            {{- else }}
            allowPrivilegeEscalation: true
            runAsNonRoot: false
            runAsUser: 0
            {{- end }}
            readOnlyRootFilesystem: false
            privileged: false
            capabilities:
              drop:
              - all
              add:
              - CHOWN
              - DAC_OVERRIDE
              - FOWNER
              - FSETID
              - KILL
              - SETGID
              - SETUID
              - SETPCAP
              - NET_BIND_SERVICE
              - NET_RAW
              - SYS_CHROOT
              - MKNOD
              - AUDIT_WRITE
              - SETFCAP
        volumeMounts:
          - name: logs-sharing
            mountPath: /profile/logs/container
          - name: cores-sharing
            mountPath: /profile/cores/container
      {{- if $.Values.common.bindingConfigMap }}
          - name: config-volume
            mountPath: /SETUP/ext-config/config.properties
            subPath: config.properties
            readOnly: false
      {{- end }}
      {{- if $.Values.hclCache.configMap }}
          - name: hcl-cache-config
            mountPath: /SETUP/hcl-cache/cache_cfg-ext.yaml
            subPath: cache_cfg-ext.yaml
          - name: hcl-cache-config
            mountPath: /SETUP/hcl-cache/redis_cfg.yaml
            subPath: redis_cfg.yaml
      {{- end }}
      {{- if and (not $.Values.global.sofySandboxContext) ($.Values.searchAppSlave.userScripts.enabled) }}
          - name:  user-scripts
            mountPath: /SETUP/user_scripts
      {{- end }}
      {{- if and $.Values.global.sofySandboxContext $.Values.searchAppSlave.demoPack.enabled }}
          - name:  demopack
            mountPath: /SETUP/user_scripts
      {{- end }}
{{- end }}
