{{- if and .Values.ingress.enabled (eq .Values.ingress.ingressController "emissary") (eq $.Values.common.searchEngine "solr") -}}
{{- $envTypeList := splitList "," (nospace .Values.common.environmentType) -}}
{{- range $envType := $envTypeList }}
{{- if ne $envType "share" }}
{{- $ingress_conf := $.Values.ingress.solrsearch.auth }}
{{- if eq $envType "live" }}
{{ $ingress_conf = $.Values.ingress.solrsearch.live }}
{{- end }}
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: commerce-{{ $envType }}-solrsearch-domain-host
spec:
  {{- if or $.Values.global.emissaryID $ingress_conf.ingressClass }}
  ambassador_id: [ '{{ default $.Values.global.emissaryID $ingress_conf.ingressClass }}' ]
  {{- end }}
  hostname: {{ tpl ($ingress_conf.domain | toString) $ }}
  acmeProvider:
    authority: none
  tlsSecret:
    name: {{ default (printf "%s%s%s-certificate" $.Values.common.tenant $.Values.common.environmentName $envType) ($ingress_conf.tlsSecret) }}
---
{{- if eq $envType "auth"}}
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: commerce-{{ $envType }}-solrsearch-domain-mapping
spec:
  {{- if or $.Values.global.emissaryID $ingress_conf.ingressClass }}
  ambassador_id: [ '{{ default $.Values.global.emissaryID $ingress_conf.ingressClass }}' ]
  {{- end }}
  prefix: /
  hostname: {{ tpl ($ingress_conf.domain | toString) $ }}
  host_regex: false
  case_sensitive: false
  timeout_ms: 10000
  service: https://{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}search-app-master:3738
  bypass_auth: true
---
{{- else if eq $envType "live"}}
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: commerce-{{ $envType }}-solrsearchrepeater-domain-mapping
spec:
  {{- if or $.Values.global.emissaryID $ingress_conf.ingressClass }}
  ambassador_id: [ '{{ default $.Values.global.emissaryID $ingress_conf.ingressClass }}' ]
  {{- end }}
  prefix: /
  hostname: {{ tpl ($ingress_conf.domain | toString) $ }}
  host_regex: false
  case_sensitive: false
  timeout_ms: 10000
  service: https://{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}search-app-repeater:3738
  bypass_auth: true
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}