{{- $envTypeList := splitList "," (nospace .Values.common.environmentType) -}}
{{ if and (has "auth" $envTypeList) (eq .Values.common.searchEngine "solr") (.Values.searchAppMaster.shardB.enabled) (.Values.searchAppMaster.shardB.persistence.enabled) (not .Values.searchAppMaster.shardB.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Values.common.tenant }}{{ .Values.common.environmentName}}-search-shard-b-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app: HCL-Commerce
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "-" }}
    release: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  accessModes:
  - {{ .Values.searchAppMaster.shardB.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.searchAppMaster.shardB.persistence.storage }}
  {{- if include "rwx.shardB.storageclass.name" $ }}
  storageClassName: {{ include "rwx.shardB.storageclass.name" $ }}
  {{- end }}
{{- end }}