{{- if not .Values.common.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-commerce
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.backwardCompatibility.ingressFormatUpgrade.enabled }}
    "helm.sh/hook": pre-install,pre-upgrade
    {{- else }}
    "helm.sh/hook": pre-install
    {{- end }}
    "helm.sh/hook-weight": "0"
  labels:
    app.kubernetes.io/name: HCL-Commerce
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "-" | replace "+" "-" }}
    app.kubernetes.io/name: {{ include "name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
{{- end }}