{{- if and (eq .Values.common.searchEngine "elastic") (.Values.storeWeb.enabled) -}}
{{- $envTypeList := splitList "," (nospace .Values.common.environmentType) -}}
{{- range $envType := $envTypeList -}}
{{- if ne $envType "share" -}}
{{- $_ := set $ "envType" $envType }}
######################################################
# Licensed Materials - Property of HCL Technologies
#  HCL Commerce
#  (C) Copyright HCL Technologies Limited 1996, 2020
######################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: HCL-Commerce
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "-" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    app.kubernetes.io/name: {{ include "name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
  name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}{{ $.Values.storeWeb.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    matchLabels:
      chart: {{ $.Chart.Name }}
      release: {{ $.Release.Name }}
      heritage: {{ $.Release.Service }}
      component: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}{{ $.Values.storeWeb.name }}
      group: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}
  replicas: {{ $.Values.storeWeb.replica }}
  template:
    metadata:
      annotations:
        productName: "HCL Commerce"
        productVersion: {{ $.Values.common.productVersion | quote }}
      labels:
        app: HCL-Commerce
        chart: {{ $.Chart.Name }}
        release: {{ $.Release.Name }}
        heritage: {{ $.Release.Service }}
        component: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}{{ $.Values.storeWeb.name }}
        group: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}
        app.kubernetes.io/name: {{ include "name" $ }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
    spec:
      {{- if $.Values.storeWeb.nodeSelector }}
      nodeSelector:
{{ toYaml $.Values.storeWeb.nodeSelector | indent 8 }}
      {{- end }}
      affinity:
        nodeAffinity:
           {{- if $.Values.storeWeb.nodeLabel }}
           requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: wc-node-select-flag
                  operator: In
                  values:
                  - {{ $.Values.storeWeb.nodeLabel }}
           {{- else }}
           requiredDuringSchedulingIgnoredDuringExecution:
           {{- include "nodeAffinityRequiredDuringScheduling" $ | indent 8 }}
           {{- end }}
           preferredDuringSchedulingIgnoredDuringExecution:
           {{- include "nodeAffinityPreferredDuringScheduling" $ | indent 8 }}
      {{- include "storeweb-podAntiAffinity" $ | indent 6 }}
      hostNetwork: false
      hostPID: false
      hostIPC: false
      serviceAccountName: {{ $.Values.common.serviceAccountName | default (printf "%s-commerce" $.Release.Name) }}
      initContainers:
      - name: store-dependence-check
        image: "{{ include "image.repo" $ }}{{ $.Values.supportC.image }}:{{ $.Values.supportC.tag }}"
        tty: true
        {{- if $.Values.common.imagePullPolicy }}
        imagePullPolicy: {{ $.Values.common.imagePullPolicy }}
        {{- end }}
        args: ['depcheck', '-component','store-web','-tenant',{{ $.Values.common.tenant }},'-env',{{ $.Values.common.environmentName}},'-envtype',{{ $envType }},'-namespace',{{ $.Release.Namespace }},'-interval_time','20','-expect_during_time','900','-timeout','5','-spiuser_pwd_encrypte',{{ $.Values.common.spiUserPwdBase64 }}]
      {{- if $.Values.vaultconsul.enabled }}
      - name: vault-dependence-check
        image: "{{ include "image.repo" $ }}{{ $.Values.supportC.image }}:{{ $.Values.supportC.tag }}"
        tty: true
        {{- if $.Values.common.imagePullPolicy }}
        imagePullPolicy: {{ $.Values.common.imagePullPolicy }}
        {{- end }}
        args: ['depcheck', '-component','vault','-namespace',{{ $.Release.Namespace }},'-interval_time','10','-expect_during_time','120','-timeout','5']
      {{- end }}
      volumes:
        - name: logs-sharing
          emptyDir: {}
      {{- if $.Values.assetsPVC.enabled }}
        - name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}-assets-volume
          persistentVolumeClaim:
            {{- if get $.Values.assetsPVC.existingClaim $envType }}
            claimName: {{ get $.Values.assetsPVC.existingClaim $envType }}
            {{- else }}
            claimName: commerce-{{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}-assets-pvc
            {{- end }}
      {{- end }}
      {{- if $.Values.common.bindingConfigMap }}
        - name: config-volume
          configMap:
            name: {{ $.Values.common.bindingConfigMap }}
      {{- end }}
      {{- if include "image.pull.secret" $ }}
      imagePullSecrets:
        - name: {{ include "image.pull.secret" $ }}
      {{- end }}
      containers:
      - name: store-web
        image: "{{ include "image.repo" $ }}{{ $.Values.storeWeb.image }}:{{ $.Values.storeWeb.tag }}"
        {{- if $.Values.common.imagePullPolicy }}
        imagePullPolicy: {{ $.Values.common.imagePullPolicy }}
        {{- end }}
        resources:
{{ toYaml $.Values.storeWeb.resources | indent 12 }}
        env:
        - name: "LICENSE"
          value: {{ $.Values.license | quote }}
        {{- if $.Values.common.timezone }}
        - name: "TZ"
          value: {{ $.Values.common.timezone | quote }}
        {{- end }}
        - name: "CONFIGURE_MODE"
          value: {{ $.Values.common.configureMode | quote }}        
        - name: "ENVIRONMENT"
          value: {{ $.Values.common.environmentName | quote }}
        - name: "TENANT"
          value: {{ $.Values.common.tenant | quote }}
        - name: "ENVTYPE"
          value: {{ $envType | quote }}
        {{- if $.Values.logging.jsonLogging.enabled }}
        - name: "ENABLE_JSON_LOGGING"
          value: "true"
        {{- end }}
        - name: "DOMAIN_NAME"
          value: "{{ $.Release.Namespace }}.svc.cluster.local"
        {{- if $.Values.global.sofySolutionContext }}
        - name: "EXTERNAL_DOMAIN_NAME"
        {{- if $.Values.global.domain }}
          value: {{ $.Values.global.domain }}
        {{- else }}
          valueFrom:
              configMapKeyRef:
                name: {{ $.Release.Name }}-domain
                key: HOST
        {{- end }}
        {{- else }} # not sofy
        - name: "EXTERNAL_DOMAIN_NAME"
          value: "{{ trimPrefix "." $.Values.common.externalDomain }}"
        {{- end }}
        - name: "VAULT_CA"
          value: {{ $.Values.vaultCA.enabled | quote }}
        {{- if (or (eq $.Values.common.configureMode "Vault") $.Values.vaultCA.enabled) }}
        - name: "VAULT_URL"
          value: {{ $.Values.common.vaultUrl | quote  }}
        {{- if $.Values.common.vaultTokenSecret }}
        - name: "VAULT_TOKEN"
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.common.vaultTokenSecret }}
              key: VAULT_TOKEN
        {{- end }}
        {{- end }}
{{- if get $.Values.storeWeb.envParameters $envType }}
     {{- range $key, $value := get $.Values.storeWeb.envParameters $envType }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
     {{- end }}
{{- end }}
        ports:
        - containerPort: 6443
          name: port6443
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /.healthcheck
            port: 6443
            scheme: HTTPS
          initialDelaySeconds: 240
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /.healthcheck
            port: 6443
            scheme: HTTPS
        securityContext:
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            runAsUser: 0
            privileged: false
            capabilities:
              drop:
              - all
              add:
              - CHOWN
              - DAC_OVERRIDE
              - FOWNER
              - FSETID
              - KILL
              - SETGID
              - SETUID
              - SETPCAP
              - NET_BIND_SERVICE
              - NET_RAW
              - SYS_CHROOT
              - MKNOD
              - AUDIT_WRITE
              - SETFCAP
        volumeMounts:
          - name: logs-sharing
            mountPath: /opt/WebSphere/HTTPServer/logs/container
        {{- if $.Values.assetsPVC.enabled }}
          - name:  {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}-assets-volume
            mountPath: /SETUP/app/assets
        {{- end }}
        {{- if $.Values.common.bindingConfigMap }}
          - name: config-volume
            mountPath: /SETUP/ext-config/config.properties
            subPath: config.properties
            readOnly: false
        {{- end }}
{{- end }}
---
{{- end }}
{{- end }}
