{{- if and .Values.ingress.enabled (eq .Values.ingress.ingressController "emissary") -}}
{{- $envTypeList := splitList "," (nospace .Values.common.environmentType) -}}
{{- range $envType := $envTypeList }}
{{- if ne $envType "share" }}
{{- $ingress_conf := $.Values.ingress.transaction.auth }}
{{- if eq $envType "live" }}
{{ $ingress_conf = $.Values.ingress.transaction.live }}
{{- end }}
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: commerce-{{ $envType }}-transaction-domain-host
spec:
  {{- if or $.Values.global.emissaryID $ingress_conf.ingressClass }}
  ambassador_id: [ '{{ default $.Values.global.emissaryID $ingress_conf.ingressClass }}' ]
  {{- end }}
  hostname: {{ tpl ($ingress_conf.domain | toString) $ }}
  acmeProvider:
    authority: none
  tlsSecret:
    name: {{ default (printf "%s%s%s-certificate" $.Values.common.tenant $.Values.common.environmentName $envType) ($ingress_conf.tlsSecret) }}
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: commerce-{{ $envType }}-transaction-domain-mapping
spec:
  {{- if or $.Values.global.emissaryID $ingress_conf.ingressClass }}
  ambassador_id: [ '{{ default $.Values.global.emissaryID $ingress_conf.ingressClass }}' ]
  {{- end }}
  prefix: /
  hostname: {{ tpl ($ingress_conf.domain | toString) $ }}
  host_regex: false
  case_sensitive: false
  timeout_ms: 10000
  service: https://{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}ts-app:5443
  bypass_auth: true
---
{{- if $.Values.tsApp.wasAdminConsole.enabled }}
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: commerce-{{ $envType }}-transaction-domain-was-console-mapping
spec:
  {{- if or $.Values.global.emissaryID $ingress_conf.ingressClass }}
  ambassador_id: [ '{{ default $.Values.global.emissaryID $ingress_conf.ingressClass }}' ]
  {{- end }}
  prefix: /ibm/console
  rewrite: /ibm/console
  hostname: {{ tpl ($ingress_conf.domain | toString) $ }}
  host_regex: false
  case_sensitive: false
  timeout_ms: 10000
  service: https://{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}ts-web:9043
  bypass_auth: true
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}