{{- if .Values.xcApp.enabled }}
{{- $envTypeList := splitList "," (nospace .Values.common.environmentType) }}
{{- range $envType := $envTypeList }}
{{- if ne $envType "share" }}
{{- $_ := set $ "envType" $envType }}
######################################################
# Licensed Materials - Property of HCL Technologies
#  HCL Commerce
#  (C) Copyright HCL Technologies Limited 1996, 2020
######################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}{{$.Values.xcApp.name}}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: HCL-Commerce
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "-" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    app.kubernetes.io/name: {{ include "name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  selector:
    matchLabels:
      {{- if $.Values.backwardCompatibility.selector.app }}
      app: {{ $.Values.backwardCompatibility.selector.app }}
      {{- end }}
      {{- if $.Values.backwardCompatibility.selector.chart }}
      chart: {{ $.Values.backwardCompatibility.selector.chart }}
      {{- else }}
      chart: {{ $.Chart.Name }}
      {{- end }}
      release: {{ $.Release.Name }}
      heritage: {{ $.Release.Service }}
      component: {{ $.Values.common.tenant }}{{$.Values.common.environmentName}}{{ $envType }}{{$.Values.xcApp.name}}
      group: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}
      {{- range $key, $value := $.Values.backwardCompatibility.selector.extraSelector }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
  replicas: {{ $.Values.xcApp.replica }}
  template:
    metadata:
      annotations:
        productName: "HCL Commerce"
        productVersion: {{ $.Values.common.productVersion | quote }}
        {{- if and ($.Values.metrics.enabled) ($.Values.metrics.prometheusAnnotations.enabled) }}
        prometheus.io/scrape: "true"
        prometheus.io/path: /monitor/metrics
        prometheus.io/port: "9280"
        {{- end }}
      labels:
        {{- if $.Values.backwardCompatibility.selector.app }}
        app: {{ $.Values.backwardCompatibility.selector.app }}
        {{- else }}
        app: HCL-Commerce
        {{- end }}
        {{- if $.Values.backwardCompatibility.selector.chart }}
        chart: {{ $.Values.backwardCompatibility.selector.chart }}
        {{- else }}
        chart: {{ $.Chart.Name }}
        {{- end }}
        release: {{ $.Release.Name }}
        heritage: {{ $.Release.Service }}
        component: {{ $.Values.common.tenant }}{{$.Values.common.environmentName}}{{ $envType }}{{$.Values.xcApp.name}}
        group: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}
        app.kubernetes.io/name: {{ include "name" $ }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
        {{- range $key, $value := $.Values.backwardCompatibility.selector.extraSelector }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
    spec:
      {{- if $.Values.xcApp.nodeSelector }}
      nodeSelector:
{{ toYaml $.Values.xcApp.nodeSelector | indent 8 }}
      {{- end }}
      affinity:
        nodeAffinity:
           {{- if $.Values.xcApp.nodeLabel }}
           requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: wc-node-select-flag
                  operator: In
                  values:
                  - {{ $.Values.xcApp.nodeLabel }}
           {{- else }}
           requiredDuringSchedulingIgnoredDuringExecution:
           {{- include "nodeAffinityRequiredDuringScheduling" $ | indent 8 }}
           {{- end }}
           preferredDuringSchedulingIgnoredDuringExecution:
           {{- include "nodeAffinityPreferredDuringScheduling" $ | indent 8 }}
      {{- include "xcapp-podAntiAffinity" $ | indent 6 }}
      hostNetwork: false
      hostPID: false
      hostIPC: false
      serviceAccountName: {{ $.Values.common.serviceAccountName | default (printf "%s-commerce" $.Release.Name) }}
      securityContext:
        fsGroup: 1000
      {{- if or (and (not $.Values.global.sofySandboxContext) ($.Values.xcApp.userScripts.enabled)) (and $.Values.global.sofySandboxContext $.Values.xcApp.demoPack.enabled) }}
      initContainers:
      {{- end }}
      {{- if and (not $.Values.global.sofySandboxContext) ($.Values.xcApp.userScripts.enabled) }}
      - name: user-script-transfer
        image: "{{ include "image.repo" $ }}{{ $.Values.xcApp.userScripts.initContainer.image }}:{{ $.Values.xcApp.userScripts.initContainer.tag }}"
        {{- if $.Values.common.imagePullPolicy }}
        imagePullPolicy: {{ $.Values.common.imagePullPolicy }}
        {{- end }}
        command: 
{{ toYaml $.Values.xcApp.userScripts.initContainer.command | indent 10 }}
        args:
{{ toYaml $.Values.xcApp.userScripts.initContainer.args | indent 10 }}
        {{- if $.Values.xcApp.userScripts.initContainer.env }}
        env:
          {{- range $key, $value := $.Values.xcApp.userScripts.initContainer.env }}
          - name: {{ $key | quote}}
            value: {{ $value | quote}}
          {{- end }}
        {{- end }}
        volumeMounts:
          - name:  user-scripts
            mountPath: /data
      {{- end }}
      {{- if and $.Values.global.sofySandboxContext $.Values.xcApp.demoPack.enabled }}
      - name: demo-pack-transfer
        image: "{{ $.Values.global.hclPreviewImageRegistry }}/{{ $.Values.xcApp.demoPack.initContainer.image }}:{{ $.Values.xcApp.demoPack.initContainer.tag }}"
        {{- if $.Values.common.imagePullPolicy }}
        imagePullPolicy: {{ $.Values.common.imagePullPolicy }}
        {{- end }}
        command: 
{{ toYaml $.Values.xcApp.demoPack.initContainer.command | indent 10 }}
        args:
{{ toYaml $.Values.xcApp.demoPack.initContainer.args | indent 10 }}
        {{- if $.Values.xcApp.demoPack.initContainer.env }}
        env:
          {{- range $key, $value := $.Values.xcApp.demoPack.initContainer.env }}
          - name: {{ $key | quote}}
            value: {{ $value | quote}}
          {{- end }}
        {{- end }}
        volumeMounts:
          - name:  demopack
            mountPath: /data
      {{- end }}
      volumes:
        - name: logs-sharing
          emptyDir: {}
        - name: cores-sharing
        {{- if get $.Values.xcApp.coresSharingPersistentVolumeClaim $envType }}
          persistentVolumeClaim:
            claimName: {{ get $.Values.xcApp.coresSharingPersistentVolumeClaim $envType }}
        {{- else }}
          emptyDir: {}
        {{- end }}
      {{- if $.Values.common.bindingConfigMap }}
        - name: config-volume
          configMap:
            name: {{ $.Values.common.bindingConfigMap }}
      {{- end }}
      {{- if $.Values.hclCache.configMap }}
        - name: hcl-cache-config
          configMap:
            name: {{ include "hcl.cache.configmap.name" $ | quote }}
      {{- end }}
      {{- if and (not $.Values.global.sofySandboxContext) ($.Values.xcApp.userScripts.enabled) }}
        - name: user-scripts
          emptyDir: {}
      {{- end }}
      {{- if and $.Values.global.sofySandboxContext $.Values.xcApp.demoPack.enabled }}
        - name: demopack
          emptyDir: {}
      {{- end }}
      {{- if include "image.pull.secret" $ }}
      imagePullSecrets:
        - name: {{ include "image.pull.secret" $ }}
      {{- end }}
      containers:
      - name: xc-app
        image: "{{ include "image.repo" $ }}{{$.Values.xcApp.image}}:{{ $.Values.xcApp.tag }}"
        {{- if $.Values.common.imagePullPolicy }}
        imagePullPolicy: {{ $.Values.common.imagePullPolicy }}
        {{- end }}
        resources:
{{ toYaml $.Values.xcApp.resources | indent 12 }}
        env:
        - name: "LICENSE"
          value: {{ $.Values.license | quote }}
        {{- if $.Values.common.commerceVersion }}
        {{- if (or (eq $.Values.common.commerceVersion "9.0.0.1") (eq $.Values.common.commerceVersion "9.0.0.0")) }}
          {{- if $.Values.common.overridePreconfig }}
        - name: "OVERRIDE_PRECONFIG"
          value: {{ $.Values.common.overridePreconfig | quote }}
          {{- end }}
        {{- end}}
        {{- else }}
        - name: "CONFIGURE_MODE"
          value: {{ $.Values.common.configureMode | quote }}
        {{- end }}
        {{- if $.Values.common.timezone }}
        - name: "TZ"
          value: {{ $.Values.common.timezone | quote }}
        {{- end }}
        - name: "ENVIRONMENT"
          value: {{ $.Values.common.environmentName | quote }}
        - name: "TENANT"
          value: {{$.Values.common.tenant | quote}}
        - name: "ENVTYPE"
          value: {{ $envType | quote }}
        {{- if $.Values.logging.jsonLogging.enabled }}
        - name: "ENABLE_JSON_LOGGING"
          value: "true"
        {{- end }}
        - name: "DOMAIN_NAME"
          value: "{{ $.Release.Namespace }}.svc.cluster.local"
        - name: "VAULT_CA"
          value: {{ $.Values.vaultCA.enabled | quote }}
        - name: "SPIUSER_NAME"
          value: {{ $.Values.common.spiUserName | quote }}
        - name: "SPIUSER_PWD"
          value: {{ $.Values.common.spiUserPwdAes | quote }}
        {{- if $.Values.metrics.enabled }}
        - name: "EXPOSE_METRICS"
          value: "true"
        {{- end }}
        {{- if (or (eq $.Values.common.configureMode "Vault") $.Values.vaultCA.enabled) }}
        - name: "VAULT_URL"
          value: {{ $.Values.common.vaultUrl | quote }}
        {{- if $.Values.common.vaultTokenSecret }}
        - name: "VAULT_TOKEN"
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.common.vaultTokenSecret }}
              key: VAULT_TOKEN
        {{- end }}
        {{- end }}
        {{- if $.Values.common.ipv6Enabled }}
        - name: "IPV6_ENABLED"
          value: "true"
        {{- end }}
{{- if get $.Values.xcApp.envParameters $envType }}
     {{- range $key, $value := get $.Values.xcApp.envParameters $envType }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
     {{- end }}
{{- end }}
        ports:
        - containerPort: 9080
          name: port9080
        - containerPort: 9443
          name: port9443
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 9443
            scheme: HTTPS
          initialDelaySeconds: 60
          timeoutSeconds: 100
        livenessProbe:
          httpGet:
            path: /
            port: 9443
            scheme: HTTPS
          initialDelaySeconds: 240
          timeoutSeconds: 100
        securityContext:
            {{- if $.Values.common.runAsNonRoot.enabled }}
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            {{- else }}
            allowPrivilegeEscalation: true
            runAsNonRoot: false
            runAsUser: 0
            {{- end }}
            readOnlyRootFilesystem: false
            privileged: false
            capabilities:
              drop:
              - all
              add:
              - CHOWN
              - DAC_OVERRIDE
              - FOWNER
              - FSETID
              - KILL
              - SETGID
              - SETUID
              - SETPCAP
              - NET_BIND_SERVICE
              - NET_RAW
              - SYS_CHROOT
              - MKNOD
              - AUDIT_WRITE
              - SETFCAP
        volumeMounts:
          - name: logs-sharing
            mountPath: /opt/WebSphere/Liberty/usr/servers/default/logs/container
          - name: cores-sharing
            mountPath: /opt/WebSphere/Liberty/usr/servers/default/cores/container
      {{- if $.Values.common.bindingConfigMap }}
          - name: config-volume
            mountPath: /SETUP/ext-config/config.properties
            subPath: config.properties
            readOnly: false
      {{- end }}
      {{- if $.Values.hclCache.configMap }}
          - name: hcl-cache-config
            mountPath: /SETUP/hcl-cache/cache_cfg-ext.yaml
            subPath: cache_cfg-ext.yaml
          - name: hcl-cache-config
            mountPath: /SETUP/hcl-cache/redis_cfg.yaml
            subPath: redis_cfg.yaml
      {{- end }}
      {{- if and (not $.Values.global.sofySandboxContext) ($.Values.xcApp.userScripts.enabled) }}
          - name:  user-scripts
            mountPath: /SETUP/user_scripts
      {{- end }}
      {{- if and $.Values.global.sofySandboxContext $.Values.xcApp.demoPack.enabled }}
          - name:  demopack
            mountPath: /SETUP/user_scripts
      {{- end }}
{{- end }}
---
{{- end }}
{{- end }}
