##
# This values yaml file provide override values to deploy ppc64le redis service using bitnami redis helm chart 
# for HCL Commerce
#   - chart version: 17.1.5
#   - redis app version: 7.0.4
# 
# To Deploy ppc64le redis using this sample values
# 1. Create a namespace
#    kubectl create ns redis
# 2. Add helm repo
#    helm repo add bitnami https://charts.bitnami.com/bitnami
# 3. Deploy Redis using this override values
#    helm install my-redis bitnami/redis -n redis -f redis-values.yaml --version "17.1.5"
# 4. Monitor deployment until all pods are healthy
# 
# To get the complete values.yaml file, please visit 
#   https://github.com/bitnami/charts/blob/e9081af51813fa0fc59f5a3e0d7bbc68c11ce71e/bitnami/redis/values.yaml
#
# To get more information related to this version of redis helm chart, please visit
#   https://github.com/bitnami/charts/blob/e9081af51813fa0fc59f5a3e0d7bbc68c11ce71e/bitnami/redis/README.md
##
architecture: standalone
fullnameOverride: "hcl-commerce-redis"
replica:
  replicaCount: 0
image:
  registry: icr.io/ppc64le-oss
  repository: redis-ppc64le
  tag: v7.0.4-bv
  pullPolicy: IfNotPresent
auth:
  enabled: false
serviceAccount:
  create: false
  name: "default"
master:
  disableCommands: []
  persistence:
    enabled: false
  ## @param master.nodeSelector Node labels for Redis&reg; master pods assignment
  ## ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector: {}
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 4Gi
  configuration: |-
    appendonly no
    save ""
    maxmemory 3000mb
    maxmemory-policy volatile-lru