##
# This values yaml file provide override values to deploy elasticsearch helm chart 
# for HCL Commerce
#   - chart version: 7.17.3
#   - elasticsearch app version: 7.17.3
# 
# To Deploy elasticsearch using this sample values
# 1. Create a namespace
#    kubectl create ns elastic
# 2. Add helm repo
#    helm repo add elastic https://helm.elastic.co
# 3. Deploy elasticsearch using this override values
#    helm install elasticsearch elastic/elasticsearch -n elastic -f elasticsearch-values.yaml --version "7.17.3"
# 4. Monitor deployment until all pods are healthy
# 
# To get the complete values.yaml file, please visit 
#   https://github.com/elastic/helm-charts/blob/v7.17.3/elasticsearch/values.yaml
#
# To get more information related to this version of elasticsearch helm chart, please visit
#   https://github.com/elastic/helm-charts/blob/v7.17.3/elasticsearch/README.md
##
fullnameOverride: "hcl-commerce-elasticsearch"
imageTag: "7.17.3"
replicas: 1
minimumMasterNodes: 1
esJavaOpts: "-Xmx6g -Xms6g"
nodeSelector: {}
resources:
  requests:
    cpu: "1000m"
    memory: "6Gi"
  limits:
    cpu: "2000m"
    memory: "8Gi"
esConfig:
  elasticsearch.yml: |
    indices.query.bool.max_clause_count: 100000
    xpack.monitoring.collection.enabled: true
    http.max_content_length: 1000mb