##
# This values yaml file provide override values to deploy bitnami redis helm chart 
# for HCL Commerce
#   - chart version: 20.1.7
#   - redis app version: 7.4.1
# 
# To Deploy redis using this sample values
# 1. Create a namespace
#    kubectl create ns redis
# 2. Add helm repo
#    helm repo add bitnami https://charts.bitnami.com/bitnami
# 3. Deploy Redis using this override values
#    helm install my-redis bitnami/redis -n redis -f redis-values.yaml --version "20.1.7"
# 4. Monitor deployment until all pods are healthy
# 
# To get the complete values.yaml file, please visit 
#   https://github.com/bitnami/charts/blob/bc01e03cea20cd93fdd43a4fece348aabb3f1ea4/bitnami/redis/values.yaml

#
# To get more information related to this version of redis helm chart, please visit
#   https://github.com/bitnami/charts/blob/bc01e03cea20cd93fdd43a4fece348aabb3f1ea4/bitnami/redis/README.md
##
architecture: standalone
fullnameOverride: "hcl-commerce-redis"
replica:
  replicaCount: 0
image:
  registry: docker.io
  repository: bitnami/redis
  tag: 7.4.1-debian-12-r1
  pullPolicy: IfNotPresent
auth:
  enabled: false
networkPolicy:
  enabled: false
serviceAccount:
  create: false
  name: "default"
master:
  disableCommands: []
  serviceAccount:
    create: false
    name: "default"
  persistence:
    enabled: false
  ## @param master.nodeSelector Node labels for Redis&reg; master pods assignment
  ## ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector: {}
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 4Gi
  configuration: |-
    appendonly no
    save ""
    maxmemory 3000mb
    maxmemory-policy volatile-lru