{{- $root := . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-consul
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      component: vault-consul
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version}}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        component: vault-consul
    spec:
      {{- if .Values.vaultConsul.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.vaultConsul.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.vaultConsul.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.vaultConsul.imagePullSecret }}
      {{- end }}
      securityContext:
        fsGroup: 1000
      containers:
        - name: vault
          resources:
{{ toYaml .Values.vaultConsul.vaultResources | indent 12 }}
          image: {{ .Values.vaultConsul.imageRepo }}{{ .Values.vaultConsul.vaultImageName }}:{{ .Values.vaultConsul.vaultImageTag }}
          imagePullPolicy: {{ .Values.vaultConsul.imagePullPolicy }}
          securityContext:
            {{- if $.Values.common.runAsNonRoot }}
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 100
            runAsGroup: 1000
            {{- else }}
            allowPrivilegeEscalation: true
            runAsNonRoot: false
            runAsUser: 0
            {{- end }}
            readOnlyRootFilesystem: false
            privileged: false
            capabilities:
              drop:
              - all
              add:
              - CHOWN
              - DAC_OVERRIDE
              - FOWNER
              - FSETID
              - KILL
              - SETGID
              - SETUID
              - SETPCAP
              - NET_BIND_SERVICE
              - NET_RAW
              - SYS_CHROOT
              - MKNOD
              - AUDIT_WRITE
              - SETFCAP
          ports:
          - containerPort: 8200
            name: port8200
          livenessProbe:
            tcpSocket:
              port: 8200
            initialDelaySeconds: 600
            timeoutSeconds: 300
          readinessProbe:
            httpGet:
              path: /ui/
              port: 8200
          {{ if .Values.vaultConsul.externalCA.enabled }}
          volumeMounts:
          - name: external-ca-volume
            mountPath: /vault/config/ca
          {{- end }}
          {{- if and (.Values.vaultConsul.vaultLoadDataWithSecret.enabled) (.Values.vaultConsul.vaultLoadDataWithSecret.secretName) }}
          - name: vault-data-secret
            mountPath: /vault/config/secret
            readOnly: true
          {{- end }}
          command:
            - "/bin/sh"
            - "-ec"
            - |
              vault server -dev -dev-root-token-id={{ .Values.vaultConsul.vaultToken }} -dev-listen-address="0.0.0.0:8200"
          {{- if .Values.vaultConsul.vaultLoadData }}
          lifecycle:
            postStart:
              exec: 
                command:
                  - "/bin/sh"
                  - "-ec"
                  - |
                    export VAULT_ADDR=http://127.0.0.1:8200
                    export VAULT_TOKEN={{ .Values.vaultConsul.vaultToken }}
                    TIMEOUT=$(( `date +%s` + 60 )); until vault status || [ `date +%s` -gt $TIMEOUT ]; do sleep 1; done
                    vault secrets enable -path {{ .Values.common.tenant }} generic
                    vault secrets enable -path=selfserve_production_pki -description="SelfServe Root CA" -max-lease-ttl=87600h pki
                    {{- if .Values.vaultConsul.externalCA.enabled }}
                    cat /vault/config/ca/tls.key > /vault/ca.pem
                    cat /vault/config/ca/tls.crt >> /vault/ca.pem
                    vault write selfserve_production_pki/config/ca pem_bundle="@/vault/ca.pem"
                    {{- else }}
                    vault write selfserve_production_pki/root/generate/internal common_name="selfserve_production_pki Root CA" ttl=87600h  key_bits=4096 exclude_cn_from_sans=true
                    {{- end }}
                    vault write selfserve_production_pki/roles/generate-cert key_bits=2048  max_ttl=8760h allow_any_name=true
                    {{- if and (.Values.vaultConsul.vaultData) (not .Values.vaultConsul.vaultLoadDataWithSecret.enabled) }}
                    {{- range $environmentName, $environmentValues := .Values.vaultConsul.vaultData }}
                    {{- range $key, $value := $environmentValues.auth }}
                    vault kv put {{ $root.Values.common.tenant }}/{{ $environmentName }}/auth/{{ $key }} value="{{ tpl ($value | toString) $ }}"
                    {{- end }}
                    {{- range $key, $value := $environmentValues.live }}
                    vault kv put {{ $root.Values.common.tenant }}/{{ $environmentName }}/live/{{ $key }} value="{{ tpl ($value | toString) $ }}"
                    {{- end }}
                    {{- range $key, $value := $environmentValues.both }}
                    vault kv put {{ $root.Values.common.tenant }}/{{ $environmentName }}/{{ $key }} value="{{ tpl ($value | toString) $ }}"
                    {{- end }}
                    {{- end }}
                    {{- end }}
                    {{- if and (.Values.vaultConsul.vaultLoadDataWithSecret.enabled) (.Values.vaultConsul.vaultLoadDataWithSecret.secretName) }}
                    while read property; do
                      entireKey=$(echo "${property}" | cut -d '=' -f1)
                      value=$(echo "${property}" | cut -d '=' -f2-)
                      vault kv put {{ $root.Values.common.tenant }}/${entireKey} value="${value}"
                    done </vault/config/secret/vault-data.properties
                    {{- end }}
          {{- end }}
        {{ if .Values.vaultConsul.externalCA.enabled }}
      volumes:
      - name: external-ca-volume
        secret:
        {{ if .Values.vaultConsul.externalCA.autoCreate }}
          secretName: {{ $root.Values.common.tenant }}vaultca-certificate
        {{ else }}
          secretName: {{ .Values.vaultConsul.externalCA.existingSecretName }}
        {{- end }}
      {{- end }}
      {{- if and (.Values.vaultConsul.vaultLoadDataWithSecret.enabled) (.Values.vaultConsul.vaultLoadDataWithSecret.secretName) }}
      - name: vault-data-secret
        secret:
          secretName: {{ .Values.vaultConsul.vaultLoadDataWithSecret.secretName }}
      {{- end }}
      serviceAccountName: {{ .Release.Name }}-commerce-vault
