{{- if and .Values.common.enableIngress (eq .Values.common.ingressController "gke") (not .Values.openshiftDeployment.enabled) }}
apiVersion: {{ .Values.common.ingressApiVersion }}
kind: Ingress
metadata:
  name: vault-{{ .Values.common.tenant }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    group: {{ .Release.Namespace }}
spec:
  ingressClassName: gce
  rules:
  - host: {{ .Values.common.subDomain }}.{{ include "external.domain" . }}
    http:
      paths:
      {{- if eq .Values.common.ingressApiVersion "extensions/v1beta1" }}      
      - path: /*
        backend:
          serviceName: vault-consul
          servicePort: 8200
      {{- else if eq .Values.common.ingressApiVersion "networking.k8s.io/v1" }}          
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: vault-consul
            port: 
              number: 8200
      {{- end }}
{{- end }}