######################################################
# Licensed Materials - Property of HCL Technologies
# HCL Commerce
# (C) Copyright HCL Technologies Limited 1996, 2020
######################################################
apiVersion: v2
description: HCL Commerce Version 9 Helm Chart
keywords:
  - HCL Commerce V9
name: hcl-commerce
version: 91.14.0
kubeVersion: ">=1.16.0-0"
appVersion: "9.1.14.0"
dependencies:
  - name: elasticsearch
    version: 7.17.3
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
  - name: zookeeper
    version: 9.2.2
    repository: https://charts.bitnami.com/bitnami
    condition: zookeeper.enabled
  - name: redis
    version: 17.13.1
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
    INDEX_LIMIT: 10
  - name: nfs-server-provisioner
    alias: commercenfs
    repository: https://kvaps.github.io/charts 
    version: 1.3.1
    condition: commercenfs.enabled
  - name: postgresql
    version: 11.9.13
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
