apiVersion: v1
kind: Secret
## feel free to update the name and namespace vaule below according to your envrionment
metadata:
  name: vault-sample-secret
  namespace: vault
type: Opaque
## property file name here has to be vault-data.properties and please do not change it
## update the properties based on your envrionments
stringData:
  vault-data.properties: |-
    dev/auth/dbHost=demodevauthdb.commerce.svc.cluster.local
    dev/auth/dbName=mall
    dev/auth/dbUser=wcs
    dev/auth/dbPassword=wcs1
    dev/auth/dbType=db2
    dev/auth/dbPort=50000
    dev/auth/dbaUser=db2inst1
    dev/auth/dbaPassword=diet4coke
    dev/auth/dbPassEncrypt=okFQawPB19Tkl1wKqQPDdAVtwz+mIgpJyqJQUuUWtyk=
    dev/auth/dbaPassEncrypt=u4h5LS/vJeSzsCfnt6NGfGHYPWK2fRq0+djkmB/iNWU=
    dev/auth/toolingBaseUrl=https://tooling.demodev.mycompany.com/tooling
    dev/auth/ts-web/extraContentSecurityPolicySource=*.demodev.mycompany.com
    dev/auth/searchQueryBaseUrl=https://search.demodevauth.mycompany.com
    dev/live/dbHost=demodevlivedb.commerce.svc.cluster.local
    dev/live/dbName=mall
    dev/live/dbUser=wcs
    dev/live/dbPassword=wcs1
    dev/live/dbType=db2
    dev/live/dbPort=50000
    dev/live/dbaUser=db2inst1
    dev/live/dbaPassword=diet4coke
    dev/live/dbPassEncrypt=okFQawPB19Tkl1wKqQPDdAVtwz+mIgpJyqJQUuUWtyk=
    dev/live/dbaPassEncrypt=u4h5LS/vJeSzsCfnt6NGfGHYPWK2fRq0+djkmB/iNWU=
    dev/live/toolingBaseUrl=https://tooling.demodev.mycompany.com/tooling
    dev/live/ts-web/extraContentSecurityPolicySource=*.demodev.mycompany.com
    dev/spiUserName=spiuser
    dev/adminSpiUserPwd=QxV7uCk6RRiwvPVaa4wdD78jaHi2za8ssjneNMdu3vgqi
    dev/authJWKS={base64}eyJrZXlzIjpbeyJrdHkiOiJSU0EiLCJraWQiOiJkZW1vS2V5IiwibiI6ImpIckkzcDRTQ1FUVUNuQmhaWkhESllzd1dCTXVhd3B5VkM2RGFLZENZeDc1MXdtRmx0bGlqY1VyOEd1WkMyLXZvMTZzT2RKZ0J5MDRwdmxydDRTc0ZDeVJvcmU1cVRyZTZJdTZfZTZ4dGRobHg1XzIzaVNmY1pqaG5tTk1SV2pFUC1wbmpZQXlWbjBINU10YVoyLXJlcDlxOUQyRENSQS15ZEtaLTZVd2t0VFZhRy1kTHNuLUNKMVNTNDQydkdybnJWYXU0b25RaVRSQlFjM2NkdHFzdDEzU3BvVHN1Y0lKblJ4RnNtUHd4M0NFUk1CTURwWi0weGRJVHJZNXVUZ3JvZnpRY21VcDRsVFZDQk9vRElJM3AyOE52YWt0TFNTWG00VmFfaHVZQlRlellwU21YWXRpTkpuY2FsUFRnREVaTkNSOWJLdXVQMjZUczMycnUtaGdnUSIsImUiOiJBUUFCIiwiZCI6ImpDZGdTc0o0Q2VsNFItWHhOaTJqX2N3TmNvSEltT0MyU2dpUjhKS1hLRjlhTWxGOHA1REF3LUxJd0xnSTNDRVVvYkN0c1k2VFlmV2JCUFBwcFJISHdPVHFjLVpMWkd5b3dtZk9LdFNfRmtjTTNJcGEtU3llcXU0MWd4bGNtZzg1Wk85UFd4eGduR3RudWJ1c3VXX3ZMSXJxWVQwUmc3UmlnR2NPVzhObVg4WlVYZTJJbDEzZi00VmVWWGRFZEE3YngwTDNkWE9HTzFCSDZJMGNGWmZIU2RYLWl1dzBiZWQ4ZUY0ODNIeDRkY3RMRkJCWmk0eC1iaWNCeEMxSDZLa2tRaThONXV4LVJVWUt0U2NzMFlzVUd3aTkwVjdBanRfY0JnckpZMGZuQk1iQUtfYzVKa0RfM09HYmw1cTZjYlBLQ2lxWDNpZi1hdEV6REkzQXM1T1hBUSIsInAiOiI4ZzRUZWliMUxoblA4NWVFZF9NYjhEcnhFV0hwNjFkTmhodEdEWHhBSGRvWk45aVJNZk00QUxvMG5uNGNwTllVcXpWY3ZmZy1KVHJ3eDJyb1dYRDZGVzlXRXJyWi1HUVpDM0dVRXgyYXRybW4wRUFFM3dhWGI1RXN5X0tfMDFjZFVDbmREU055ZGtSU1FIRTB3Z3F1QV9uTWkxV3RKS3ViVXp4NW9fQ0xJMUUiLCJxIjoibEpLaWJma2lyWU1hZmxiZEw1V0VHdlE0Y2lPaER6TFd4WVBQejlCa3pFWGdCaGxTY0VsLVhLQnh2bTFBa2dkdkhZMXVlT3IxdUhCeXBlSnhCbTNOTUtfelZjOUd5X1NUUnpabkJIajZERGZURVoybW5aWEhXSGNCMTNjQi1XcUh3c2xlaHBLZF9FOE9Db3NnM25rQjZVdDVhc3h4cy03X2FhV05yYnJwUGpFIiwiZHAiOiJwMGM1Q0tMaHItRmd4X3ZfTFJJU1RidS1HNEFxTTF6YkU0SEhzTXdjVjBVQlJvbmhGYjc3QmUycExac0QycHFrSUFtNXRRTllsMHdiV0FVMjI1RHJFMk1rX2I2cG9qSXk2S2l1WjJOX0p5WTRwZi1JSGtVazVKSlVmZ0dkdGNVdldkWUVrTzdkVElROHY1SThucGpZMTZDTFRnT0FxNlg0cXRaUlRnMlBhbkUiLCJkcSI6IlZKeUpxbzJtcFNBejExMkt5ODJmbFdZZU8wcDFMOTJwR0lVdnRVOGVDSU9HeUpKbE01TjNSak1OZEFCdU5Idk5XUXd4ck9WS21RWlpGSVc0RG93N3ZnMkdUQWttYllMVTJVcHZNc25leFZTSmZNX0drcG81RV9WNmRBWFBkd2FuV0ZRcjVBSGR2VkljVWY3WDhqc0J6cVh2LU5XRHI1QmRud0hzaE5NY2dCRSIsInFpIjoiTjdoWERqcEVCZTQxRFp0LUJCelZ4THBOSnd5ckZwSnZqZTFKVGNndkRld0Q5NDVTWWVROGROWGpsYWlVYjVYU19JWWg1dXdjM1lMOGxNeWdGUm1kNVR1c2xDcmU2VUxleGZBY1p0Q3dlVkl0WEsxdjBCUlVKSHFzRU1PZVNGdE12VU5Wdk5sRzlKbmd0OWMxTjRELWZNaVR3VkZndTBIOUFDY1RXT2VYYzZjIn1dfQ==
    dev/elasticSearchHost=hcl-commerce-elasticsearch.elastic.svc.cluster.local
    dev/elasticSearchPort=9200
    dev/elasticSearchScheme=http
    dev/nifiWebHttpPort=30600
    dev/nifiClusterIsNode=false
    dev/nifiClusterNodeProtocalPort=30600
    dev/zookeeperHost=hcl-commerce-zookeeper.zookeeper.svc.cluster.local
    dev/zookeeperPort=2181
    dev/nifiElectionMaxWait=1 min
    dev/nifiJvmHeapInit=4096m
    dev/nifiJvmHeapMax=6144m
    dev/registryHost=demodevregistry-app.commerce.svc.cluster.local
    dev/registryPort=30400
    dev/nifiHost=demodevnifi-app.commerce.svc.cluster.local
    dev/nifiPort=30600
    dev/redisHost=hcl-commerce-redis-master.redis.svc.cluster.local
    dev/redisPort=6379
    dev/searchDataQueryBaseUrl=https://query.demodev.mycompany.com
    dev/nlpEnableLanguageCode=en
    dev/deploymentType=development
    dev/sessionKeyEncrypt=4knZgrqtE6ukU79414EIZIBcrgyZM8SBZZIC2nugW/7ntRBCM3bS9TVwdHmIB1ZcxVj8/ROwMUFJxcEAQpFGew==
    dev/reactStoreMapApiKey=<reactStoreMapApiKey>
    qa/auth/dbHost=demoqaauthdb.commerce.svc.cluster.local
    qa/auth/dbName=mall
    qa/auth/dbUser=wcs
    qa/auth/dbPassword=wcs1
    qa/auth/dbType=db2
    qa/auth/dbPort=50000
    qa/auth/dbaUser=db2inst1
    qa/auth/dbaPassword=diet4coke
    qa/auth/dbPassEncrypt=okFQawPB19Tkl1wKqQPDdAVtwz+mIgpJyqJQUuUWtyk=
    qa/auth/dbaPassEncrypt=u4h5LS/vJeSzsCfnt6NGfGHYPWK2fRq0+djkmB/iNWU=
    qa/auth/toolingBaseUrl=https://tooling.demoqa.mycompany.com/tooling
    qa/auth/ts-web/extraContentSecurityPolicySource=*.demoqa.mycompany.com
    qa/auth/searchQueryBaseUrl=https://search.demoqaauth.mycompany.com
    qa/live/dbHost=demoqalivedb.commerce.svc.cluster.local
    qa/live/dbName=mall
    qa/live/dbUser=wcs
    qa/live/dbPassword=wcs1
    qa/live/dbType=db2
    qa/live/dbPort=50000
    qa/live/dbaUser=db2inst1
    qa/live/dbaPassword=diet4coke
    qa/live/dbPassEncrypt=okFQawPB19Tkl1wKqQPDdAVtwz+mIgpJyqJQUuUWtyk=
    qa/live/dbaPassEncrypt=u4h5LS/vJeSzsCfnt6NGfGHYPWK2fRq0+djkmB/iNWU=
    qa/live/toolingBaseUrl=https://tooling.demoqa.mycompany.com/tooling
    qa/live/ts-web/extraContentSecurityPolicySource=*.demoqa.mycompany.com
    qa/spiUserName=spiuser
    qa/adminSpiUserPwd=QxV7uCk6RRiwvPVaa4wdD78jaHi2za8ssjneNMdu3vgqi
    qa/authJWKS={base64}eyJrZXlzIjpbeyJrdHkiOiJSU0EiLCJraWQiOiJkZW1vS2V5IiwibiI6ImpIckkzcDRTQ1FUVUNuQmhaWkhESllzd1dCTXVhd3B5VkM2RGFLZENZeDc1MXdtRmx0bGlqY1VyOEd1WkMyLXZvMTZzT2RKZ0J5MDRwdmxydDRTc0ZDeVJvcmU1cVRyZTZJdTZfZTZ4dGRobHg1XzIzaVNmY1pqaG5tTk1SV2pFUC1wbmpZQXlWbjBINU10YVoyLXJlcDlxOUQyRENSQS15ZEtaLTZVd2t0VFZhRy1kTHNuLUNKMVNTNDQydkdybnJWYXU0b25RaVRSQlFjM2NkdHFzdDEzU3BvVHN1Y0lKblJ4RnNtUHd4M0NFUk1CTURwWi0weGRJVHJZNXVUZ3JvZnpRY21VcDRsVFZDQk9vRElJM3AyOE52YWt0TFNTWG00VmFfaHVZQlRlellwU21YWXRpTkpuY2FsUFRnREVaTkNSOWJLdXVQMjZUczMycnUtaGdnUSIsImUiOiJBUUFCIiwiZCI6ImpDZGdTc0o0Q2VsNFItWHhOaTJqX2N3TmNvSEltT0MyU2dpUjhKS1hLRjlhTWxGOHA1REF3LUxJd0xnSTNDRVVvYkN0c1k2VFlmV2JCUFBwcFJISHdPVHFjLVpMWkd5b3dtZk9LdFNfRmtjTTNJcGEtU3llcXU0MWd4bGNtZzg1Wk85UFd4eGduR3RudWJ1c3VXX3ZMSXJxWVQwUmc3UmlnR2NPVzhObVg4WlVYZTJJbDEzZi00VmVWWGRFZEE3YngwTDNkWE9HTzFCSDZJMGNGWmZIU2RYLWl1dzBiZWQ4ZUY0ODNIeDRkY3RMRkJCWmk0eC1iaWNCeEMxSDZLa2tRaThONXV4LVJVWUt0U2NzMFlzVUd3aTkwVjdBanRfY0JnckpZMGZuQk1iQUtfYzVKa0RfM09HYmw1cTZjYlBLQ2lxWDNpZi1hdEV6REkzQXM1T1hBUSIsInAiOiI4ZzRUZWliMUxoblA4NWVFZF9NYjhEcnhFV0hwNjFkTmhodEdEWHhBSGRvWk45aVJNZk00QUxvMG5uNGNwTllVcXpWY3ZmZy1KVHJ3eDJyb1dYRDZGVzlXRXJyWi1HUVpDM0dVRXgyYXRybW4wRUFFM3dhWGI1RXN5X0tfMDFjZFVDbmREU055ZGtSU1FIRTB3Z3F1QV9uTWkxV3RKS3ViVXp4NW9fQ0xJMUUiLCJxIjoibEpLaWJma2lyWU1hZmxiZEw1V0VHdlE0Y2lPaER6TFd4WVBQejlCa3pFWGdCaGxTY0VsLVhLQnh2bTFBa2dkdkhZMXVlT3IxdUhCeXBlSnhCbTNOTUtfelZjOUd5X1NUUnpabkJIajZERGZURVoybW5aWEhXSGNCMTNjQi1XcUh3c2xlaHBLZF9FOE9Db3NnM25rQjZVdDVhc3h4cy03X2FhV05yYnJwUGpFIiwiZHAiOiJwMGM1Q0tMaHItRmd4X3ZfTFJJU1RidS1HNEFxTTF6YkU0SEhzTXdjVjBVQlJvbmhGYjc3QmUycExac0QycHFrSUFtNXRRTllsMHdiV0FVMjI1RHJFMk1rX2I2cG9qSXk2S2l1WjJOX0p5WTRwZi1JSGtVazVKSlVmZ0dkdGNVdldkWUVrTzdkVElROHY1SThucGpZMTZDTFRnT0FxNlg0cXRaUlRnMlBhbkUiLCJkcSI6IlZKeUpxbzJtcFNBejExMkt5ODJmbFdZZU8wcDFMOTJwR0lVdnRVOGVDSU9HeUpKbE01TjNSak1OZEFCdU5Idk5XUXd4ck9WS21RWlpGSVc0RG93N3ZnMkdUQWttYllMVTJVcHZNc25leFZTSmZNX0drcG81RV9WNmRBWFBkd2FuV0ZRcjVBSGR2VkljVWY3WDhqc0J6cVh2LU5XRHI1QmRud0hzaE5NY2dCRSIsInFpIjoiTjdoWERqcEVCZTQxRFp0LUJCelZ4THBOSnd5ckZwSnZqZTFKVGNndkRld0Q5NDVTWWVROGROWGpsYWlVYjVYU19JWWg1dXdjM1lMOGxNeWdGUm1kNVR1c2xDcmU2VUxleGZBY1p0Q3dlVkl0WEsxdjBCUlVKSHFzRU1PZVNGdE12VU5Wdk5sRzlKbmd0OWMxTjRELWZNaVR3VkZndTBIOUFDY1RXT2VYYzZjIn1dfQ==
    qa/elasticSearchHost=hcl-commerce-elasticsearch.elastic.svc.cluster.local
    qa/elasticSearchPort=9200
    qa/elasticSearchScheme=http
    qa/zookeeperHost=hcl-commerce-zookeeper.zookeeper.svc.cluster.local
    qa/zookeeperPort=2181
    qa/nifiJvmHeapInit=4096m
    qa/nifiJvmHeapMax=6144m
    qa/redisHost=hcl-commerce-redis-master.redis.svc.cluster.local
    qa/redisPort=6379
    qa/searchDataQueryBaseUrl=https://query.demoqa.mycompany.com
    qa/nlpEnableLanguageCode=en
    qa/deploymentType=development
    qa/sessionKeyEncrypt=4knZgrqtE6ukU79414EIZIBcrgyZM8SBZZIC2nugW/7ntRBCM3bS9TVwdHmIB1ZcxVj8/ROwMUFJxcEAQpFGew==
    qa/reactStoreMapApiKey=<reactStoreMapApiKey>