######################################################
# Licensed Materials - Property of HCL Technologies
# HCL Commerce
# (C) Copyright HCL Technologies Limited 1996, 2020
######################################################
apiVersion: v2
description: HCL Commerce Version 9 Helm Chart
keywords:
  - HCL Commerce V9
name: hcl-commerce
version: 91.13.0
kubeVersion: ">=1.16.0-0"
appVersion: "9.1.13.0"
dependencies:
  - name: elasticsearch
    version: 7.17.3
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
  - name: zookeeper
    version: 9.2.2
    repository: https://charts.bitnami.com/bitnami
    condition: zookeeper.enabled
  - name: redis
    version: 17.1.5
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    version: 11.9.13
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    INDEX_LIMIT: 10