{{- $envTypeList := splitList "," (nospace .Values.common.environmentType) -}}
{{- if and (has "share" $envTypeList) (.Values.approvalApp.enabled) (not .Values.approvalApp.bootConfig.existingSecret)}}
######################################################
# Licensed Materials - Property of HCL Technologies
#  HCL Commerce
#  (C) Copyright HCL Technologies Limited 2022
######################################################
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: HCL-Commerce
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "-" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
  name: {{ .Release.Name }}-{{ .Values.common.tenant }}{{ .Values.common.environmentName}}{{.Values.approvalApp.name}}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
{{ toYaml .Values.approvalApp.bootConfig | indent 2 }}
{{- end }}