{{- if and $.Values.gateway.enabled $.Values.cacheApp.enabled -}}
{{- $envTypeList := splitList "," (nospace $.Values.common.environmentType) -}}
{{- $tenant := $.Values.common.tenant -}}
{{- $envName := $.Values.common.environmentName -}}
{{- range $envType := $envTypeList -}}
{{- if ne $envType "share" }}
{{- $gw_conf := $.Values.gateway.cache.auth }}
{{- if eq $envType "live" }}
{{ $gw_conf = $.Values.gateway.cache.live }}
{{- end }}
{{- if $gw_conf.enabled }}
######################################################
# Licensed Materials - Property of HCL Technologies
#  HCL Commerce
#  (C) Copyright HCL Technologies Limited 1996, 2026
######################################################
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $tenant }}{{ $envName }}{{ $envType }}-cache-httproute
  namespace: {{ $.Release.Namespace }}
  labels:
    app: HCL-Commerce
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "-" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    group: {{ $tenant }}{{ $envName }}{{ $envType }}
spec:
  parentRefs:
  - name: {{ include "hcl-commerce.gateway.name" $ }}
    sectionName: {{ $envType }}-cache
  hostnames:
  - {{ tpl ($gw_conf.domain | toString) $ }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ $tenant }}{{ $envName }}{{ $envType }}cache-app
      port: 40901
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
