{{- if and .Values.ingress.enabled (eq .Values.ingress.ingressController "emissary") -}}
{{- $envTypeList := splitList "," (nospace .Values.common.environmentType) -}}
{{- range $envType := $envTypeList }}
{{- if ne $envType "share" }}
{{- $ingress_conf := $.Values.ingress.cmc.auth }}
{{- if eq $envType "live" }}
{{ $ingress_conf = $.Values.ingress.cmc.live }}
{{- end }}
apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: commerce-{{ $envType }}-cmc-domain-host
spec:
  {{- if or $.Values.global.emissaryID $ingress_conf.ingressClass }}
  ambassador_id: [ '{{ default $.Values.global.emissaryID $ingress_conf.ingressClass }}' ]
  {{- end }}
  hostname: {{ tpl ($ingress_conf.domain | toString) $ }}
  acmeProvider:
    authority: none
  tlsSecret:
    name: {{ default (printf "%s%s%s-certificate" $.Values.common.tenant $.Values.common.environmentName $envType) ($ingress_conf.tlsSecret) }}
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: commerce-{{ $envType }}-cmc-domain-cmc-mapping
spec:
  {{- if or $.Values.global.emissaryID $ingress_conf.ingressClass }}
  ambassador_id: [ '{{ default $.Values.global.emissaryID $ingress_conf.ingressClass }}' ]
  {{- end }}
  prefix: /
  hostname: {{ tpl ($ingress_conf.domain | toString) $ }}
  host_regex: false
  case_sensitive: false
  timeout_ms: 10000
  service: https://{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}ts-web:8000
  bypass_auth: true
---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: commerce-{{ $envType }}-cmc-domain-tooling-mapping
spec:
  {{- if or $.Values.global.emissaryID $ingress_conf.ingressClass }}
  ambassador_id: [ '{{ default $.Values.global.emissaryID $ingress_conf.ingressClass }}' ]
  {{- end }}
  prefix: /tooling/
  rewrite: /tooling/
  hostname: {{ tpl ($ingress_conf.domain | toString) $ }}
  host_regex: false
  case_sensitive: false
  timeout_ms: 10000
  service: https://{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}tooling-web:7443
  bypass_auth: true
---
{{- if $.Values.approvalApp.enabled }}
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: commerce-{{ $envType }}-cmc-domain-approval-mapping
spec:
  {{- if or $.Values.global.emissaryID $ingress_conf.ingressClass }}
  ambassador_id: [ '{{ default $.Values.global.emissaryID $ingress_conf.ingressClass }}' ]
  {{- end }}
  prefix: /approvals
  rewrite: /approvals
  hostname: {{ tpl ($ingress_conf.domain | toString) $ }}
  host_regex: false
  case_sensitive: false
  timeout_ms: 10000
  service: https://{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}approval-app:6643
  bypass_auth: true
---
{{- if $.Values.ingress.enableManageApprovalPage }}
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: commerce-{{ $envType }}-cmc-domain-manage-approval-mapping
spec:
  {{- if or $.Values.global.emissaryID $ingress_conf.ingressClass }}
  ambassador_id: [ '{{ default $.Values.global.emissaryID $ingress_conf.ingressClass }}' ]
  {{- end }}
  prefix: /approvals/manage-approval
  rewrite: /approvals/manage-approval
  hostname: {{ tpl ($ingress_conf.domain | toString) $ }}
  host_regex: false
  case_sensitive: false
  timeout_ms: 10000
  service: https://{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}ts-web:8000
  bypass_auth: true
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}