{{- if and $.Values.gateway.enabled (eq $.Values.common.searchEngine "elastic") -}}
{{- $envTypeList := splitList "," (nospace $.Values.common.environmentType) -}}
{{- $tenant := $.Values.common.tenant -}}
{{- $envName := $.Values.common.environmentName -}}
{{- if has "share" $envTypeList }}
{{- $gw_conf := $.Values.gateway.ingest }}
######################################################
# Licensed Materials - Property of HCL Technologies
#  HCL Commerce
#  (C) Copyright HCL Technologies Limited 1996, 2026
######################################################
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $tenant }}{{ $envName }}-ingest-httproute
  namespace: {{ $.Release.Namespace }}
  labels:
    app: HCL-Commerce
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "-" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  parentRefs:
  - name: {{ include "hcl-commerce.gateway.name" $ }}
    sectionName: share-ingest
  hostnames:
  - {{ tpl ($gw_conf.domain | toString) $ }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ $tenant }}{{ $envName }}{{ $.Values.ingestApp.name }}
      port: 30800
{{- end }}
{{- end }}
