{{- $envTypeList := splitList "," (nospace .Values.common.environmentType) -}}
{{- if and (has "share" $envTypeList) (eq $.Values.common.searchEngine "elastic") (.Values.ingress.enabled) (.Values.mustgatherApp.enabled) (.Values.ingress.mustgather.enabled) (not .Values.openshiftDeployment.enabled) (ne .Values.ingress.ingressController "emissary") (ne .Values.ingress.ingressController "ambassador") }}
{{- $ingress_conf := $.Values.ingress.mustgather }}
apiVersion: {{ $.Values.ingress.apiVersion }}
kind: Ingress
metadata:
  name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}mustgather-ingress
  namespace: {{ $.Release.Namespace }}
  annotations:
    ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    {{- if eq $.Values.ingress.ingressController "gke" }}
    kubernetes.io/ingress.class: {{ default "gce" $ingress_conf.ingressClass | quote }}
    {{- end }}
    {{- if eq $.Values.ingress.ingressController "nginx" }}
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.org/ssl-services: "{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}mustgatherApp"
    {{- end }}
    {{- if $.Values.ingress.mustgather.customAnnotations }}
{{ toYaml $.Values.ingress.mustgather.customAnnotations | indent 4 }}
    {{- end }}
  labels:
    app: HCL-Commerce
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "-" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    group: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}
spec:
  {{- if eq $.Values.ingress.ingressController "nginx" }}
  ingressClassName: {{ default "nginx" $ingress_conf.ingressClass | quote }}
  {{- end }}
  tls:
  - hosts:
    - {{ tpl ($ingress_conf.domain | toString) $ }}
    secretName: {{ default (printf "%s%sshare-certificate" $.Values.common.tenant $.Values.common.environmentName) ($ingress_conf.tlsSecret) }}
  rules:
  - host: {{ tpl ($ingress_conf.domain | toString) $ }}
    http:
      paths:
      {{- if eq $.Values.ingress.apiVersion "networking.k8s.io/v1beta1" }}
      - path: {{- if eq $.Values.ingress.ingressController "nginx" }} / {{- else if eq $.Values.ingress.ingressController "gke" }} /* {{- end }}
        backend:
          serviceName: {{ .Values.common.tenant }}{{ .Values.common.environmentName }}{{.Values.mustgatherApp.name}}
          servicePort: 42021
      {{- else if eq $.Values.ingress.apiVersion "networking.k8s.io/v1" }}
      - path: {{- if eq $.Values.ingress.ingressController "nginx" }} / {{- else if eq $.Values.ingress.ingressController "gke" }} /* {{- end }}
        pathType: {{- if eq $.Values.ingress.ingressController "nginx" }} Prefix {{- else if eq $.Values.ingress.ingressController "gke" }} ImplementationSpecific {{- end }}
        backend:
          service:
            name: {{ .Values.common.tenant }}{{ .Values.common.environmentName }}{{.Values.mustgatherApp.name}}
            port:
              number: 42021
      {{- end }}
{{- end }}
---
