{{- if and .Values.orchestrationApp.enabled (eq $.Values.common.searchEngine "solr") -}}
{{- $envTypeList := splitList "," (nospace .Values.common.environmentType) -}}
{{- range $envType := $envTypeList -}}
{{- if ne $envType "share" }}
######################################################
# Licensed Materials - Property of HCL Technologies
#  HCL Commerce
#  (C) Copyright HCL Technologies Limited 2024
######################################################
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}{{$.Values.orchestrationApp.name}}
  labels:
    app: HCL-Commerce
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "-" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    component: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}{{$.Values.orchestrationApp.name}}
    group: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}
    app.kubernetes.io/name: {{ include "name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    cloud.google.com/app-protocols: '{"https-port19443":"HTTPS"}'
spec:
  type: NodePort
  ports:
  - port: 19443
    name: https-port19443
  selector:
    component: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}{{$.Values.orchestrationApp.name}}
{{- end }}
---
{{- end }}
{{- end }}