{{- if and (.Values.common.runAsNonRoot.enabled) (.Values.assetsPVC.enabled) (.Values.common.runAsNonRoot.migrateAssetsPvcFromRootToNonroot) }}
{{- $envTypeList := splitList "," (nospace .Values.common.environmentType) -}}
{{- range $envType := $envTypeList }}
{{- if ne $envType "share" }}
{{- $_ := set $ "envType" $envType }}
######################################################
# Licensed Materials - Property of HCL Technologies
#  HCL Commerce
#  (C) Copyright HCL Technologies Limited 1996, 2023
######################################################
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: HCL-Commerce
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "-" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
  name: {{ $.Release.Name }}-nonroot-update-{{ $.Values.common.tenant | lower}}{{ $.Values.common.environmentName | lower}}{{ $envType }}-{{ randAlphaNum 10 | lower }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": "hook-succeeded"
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 300
  template:
    metadata:
      {{- if $.Values.anthosDeployment.enabled }}
      annotations:
        sidecar.istio.io/inject: "false"
      {{- end }}
      labels:
        app: HCL-Commerce
        chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "-" }}
        release: {{ $.Release.Name }}
        heritage: {{ $.Release.Service }}
    spec:
      affinity:
      {{- include "nodeaffinity" $ | indent 6 }}
      hostNetwork: false
      hostPID: false
      hostIPC: false
      serviceAccountName: {{ $.Values.common.serviceAccountName | default (printf "%s-commerce" $.Release.Name) }}
      restartPolicy: Never
      volumes:
        - name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}-assets-volume
          persistentVolumeClaim:
            {{- if get $.Values.assetsPVC.existingClaim $envType }}
            claimName: {{ get $.Values.assetsPVC.existingClaim $envType }}
            {{- else }}
            claimName: commerce-{{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}-assets-pvc
            {{- end }}
      containers:
        - name: pre-upgrade-nonroot-ownership-update-{{ $.Values.common.tenant | lower}}{{ $.Values.common.environmentName | lower}}{{ $envType }}-{{ randAlphaNum 10 | lower }}
          image: registry.access.redhat.com/ubi8/ubi-micro:8.8-5
          tty: true
          {{- if $.Values.common.imagePullPolicy }}
          imagePullPolicy: {{ $.Values.common.imagePullPolicy }}
          {{- end }}
          args: ['chown','-R','1000:1000','/assets']
          securityContext:
            allowPrivilegeEscalation: true
            runAsNonRoot: false
            runAsUser: 0
            readOnlyRootFilesystem: false
            privileged: false
            capabilities:
              drop:
              - all
              add:
              - CHOWN
          volumeMounts:
            - name:  {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}-assets-volume
              mountPath: /assets          
---
{{- end }}
{{- end }}
{{- end }}