{{- range $ingress_controller := list "gke" "nginx" -}}
{{- if eq (include "hcl-commerce.hasIngressController" (list $ingress_controller $)) "true" -}}
{{- $ingress_name_suffix := "gke" -}}{{- if eq $ingress_controller "nginx" -}}{{- $ingress_name_suffix = "community-nginx" -}}{{- end -}}
{{- if and ($.Values.ingress.enabled) ($ingress_controller) (eq $.Values.common.searchEngine "elastic") ($.Values.ingress.registry.enabled) -}}
{{- $envTypeList := splitList "," (nospace $.Values.common.environmentType) -}}
{{- if has "share" $envTypeList }}
{{- $ingress_conf := $.Values.ingress.registry }}
apiVersion: {{ $.Values.ingress.apiVersion }}
kind: Ingress
metadata:
  name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}registry-{{ $ingress_name_suffix }}-ingress
  namespace: {{ $.Release.Namespace }}
  annotations:
    {{- if eq $ingress_controller "gke" }}
    {{- if $.Values.ingress.registry.gkeCustomAnnotations }}
{{ toYaml $.Values.ingress.registry.gkeCustomAnnotations | indent 4 }}
    {{- end }}
    {{- else }}
    {{- if $.Values.ingress.registry.communityNginxCustomAnnotations }}
{{ toYaml $.Values.ingress.registry.communityNginxCustomAnnotations | indent 4 }}
    {{- end }}
    {{- end }}
  labels:
    app: HCL-Commerce
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "-" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    group: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}
spec:
  {{- if eq $ingress_controller "nginx" }}
  ingressClassName: {{ default "nginx" $ingress_conf.communityNginxClass | quote }}
  {{- else if eq $ingress_controller "gke" }}
  ingressClassName: {{ default "gce" $ingress_conf.gkeClass | quote }}
  {{- end }}
  tls:
  - hosts:
    - {{ tpl ($ingress_conf.domain | toString) $ }}
    secretName: {{ default (printf "%s%sshare-certificate" $.Values.common.tenant $.Values.common.environmentName) ($ingress_conf.tlsSecret) }}
  rules:
  - host: {{ tpl ($ingress_conf.domain | toString) $ }}
    http:
      paths:
      {{- if eq $.Values.ingress.apiVersion "networking.k8s.io/v1beta1" }}
      - path: {{- if eq $ingress_controller "nginx" }} / {{- else if eq $ingress_controller "gke" }} /* {{- end }}
        backend:
          serviceName: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{$.Values.registryApp.name}}
          servicePort: 30400
      {{- else if eq $.Values.ingress.apiVersion "networking.k8s.io/v1" }}
      - path: {{- if eq $ingress_controller "nginx" }} / {{- else if eq $ingress_controller "gke" }} /* {{- end }}
        pathType: {{- if eq $ingress_controller "nginx" }} Prefix {{- else if eq $ingress_controller "gke" }} ImplementationSpecific {{- end }}
        backend:
          service:
            name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{$.Values.registryApp.name}}
            port:
              number: 30400
      {{- end }}
{{- end }}
{{- end }}
---
{{- end }}
{{- end }}