{{- if and .Values.tsDb.enabled (eq .Values.common.dbType "db2") }}
{{- $envTypeList := splitList "," (nospace .Values.common.environmentType) }}
{{- range $envType := $envTypeList }}
{{- if ne $envType "share" }}
######################################################
# Licensed Materials - Property of HCL Technologies
#  HCL Commerce
#  (C) Copyright HCL Technologies Limited 1996, 2020
######################################################
## This sample DB2 should only be used for non-production environment.
## Please see https://help.hcltechsw.com/commerce/9.1.0/install/tasks/tiginstalldb2overview.html for details
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}db
  namespace: {{ $.Release.Namespace }}
  labels:
    app: HCL-Commerce
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "-" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    app.kubernetes.io/name: {{ include "name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  selector:
    matchLabels:
      component: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}db
      group: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}
      release: {{ $.Release.Name }}
      chart: {{ $.Chart.Name }}
      heritage: {{ $.Release.Service }}
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        productName: "HCL Commerce"
        productVersion: {{ $.Values.common.productVersion | quote }}
      labels:
        component: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}db
        group: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}
        app: HCL-Commerce
        release: {{ $.Release.Name }}
        chart: {{ $.Chart.Name }}
        heritage: {{ $.Release.Service }}
    spec:
      {{- if $.Values.tsDb.nodeSelector }}
      nodeSelector:
{{ toYaml $.Values.tsDb.nodeSelector | indent 8 }}
      {{- end }}
      affinity:
        nodeAffinity:
           {{- if $.Values.tsDb.nodeLabel }}
           requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: wc-node-select-flag
                  operator: In
                  values:
                  - {{ $.Values.tsDb.nodeLabel }}
           {{- else }}
           requiredDuringSchedulingIgnoredDuringExecution:
           {{- include "nodeAffinityRequiredDuringScheduling" $ | indent 8 }}
           {{- end }}
           preferredDuringSchedulingIgnoredDuringExecution:
           {{- include "nodeAffinityPreferredDuringScheduling" $ | indent 8 }}
      hostNetwork: false
      hostPID: false
      hostIPC: false
      serviceAccountName: {{ $.Values.common.serviceAccountName | default (printf "%s-commerce" $.Release.Name) }}
      {{- if include "image.pull.secret" $ }}
      imagePullSecrets:
        - name: {{ include "image.pull.secret" $ }}
      {{- end }}
      {{- if $.Values.tsDb.persistence.enabled }}
      volumes:
        - name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}-tsdb-volume
          persistentVolumeClaim:
            {{- if $.Values.tsDb.persistence.existingClaim }}
            claimName: {{ $.Values.tsDb.persistence.existingClaim }}
            {{- else }}
            claimName: {{ $.Release.Name }}-{{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $envType }}-tsdb-pvc
            {{- end }}
      {{- if and (not $.Values.global.sofySandboxContext) ($.Values.tsDb.userScripts.enabled) }}
        - name: user-scripts
          emptyDir: {}
      {{- end }}
      {{- if and $.Values.global.sofySandboxContext $.Values.tsDb.demoPack.enabled }}
        - name: demopack
          emptyDir: {}
      {{- end }}
      initContainers:
      {{- if and (not $.Values.global.sofySandboxContext) ($.Values.tsDb.userScripts.enabled) }}
      - name: user-script-transfer
        image: "{{ include "image.repo" $ }}{{ $.Values.tsDb.userScripts.initContainer.image }}:{{ $.Values.tsDb.userScripts.initContainer.tag }}"
        {{- if $.Values.common.imagePullPolicy }}
        imagePullPolicy: {{ $.Values.common.imagePullPolicy }}
        {{- end }}
        command: 
{{ toYaml $.Values.tsDb.userScripts.initContainer.command | indent 10 }}
        args:
{{ toYaml $.Values.tsDb.userScripts.initContainer.args | indent 10 }}
        {{- if $.Values.tsDb.userScripts.initContainer.env }}
        env:
          {{- range $key, $value := $.Values.tsDb.userScripts.initContainer.env }}
          - name: {{ $key | quote}}
            value: {{ $value | quote}}
          {{- end }}
        {{- end }}
        volumeMounts:
          - name:  user-scripts
            mountPath: /data
      {{- end }}
      {{- if and $.Values.global.sofySandboxContext $.Values.tsDb.demoPack.enabled }}
      - name: demo-pack-transfer
        image: "{{ $.Values.global.hclPreviewImageRegistry }}/{{ $.Values.tsDb.demoPack.initContainer.image }}:{{ $.Values.tsDb.demoPack.initContainer.tag }}"
        {{- if $.Values.common.imagePullPolicy }}
        imagePullPolicy: {{ $.Values.common.imagePullPolicy }}
        {{- end }}
        command: 
{{ toYaml $.Values.tsDb.demoPack.initContainer.command | indent 10 }}
        args:
{{ toYaml $.Values.tsDb.demoPack.initContainer.args | indent 10 }}
        {{- if $.Values.tsDb.demoPack.initContainer.env }}
        env:
          {{- range $key, $value := $.Values.tsDb.demoPack.initContainer.env }}
          - name: {{ $key | quote}}
            value: {{ $value | quote}}
          {{- end }}
        {{- end }}
        volumeMounts:
          - name:  demopack
            mountPath: /data
      {{- end }}
      - name: pre-load-db-data
        image: "{{ include "image.repo" $ }}{{ $.Values.tsDb.image }}:{{ $.Values.tsDb.tag }}"
        {{- if $.Values.common.imagePullPolicy }}
        imagePullPolicy: {{ $.Values.common.imagePullPolicy }}
        {{- end }}
        command: ["/bin/bash"]
        args: ["-c", 'if [ ! -f /data/.preload_completed ]; then cp -rp /home/db2inst1/db2inst1/* /data; rc=$?; if [ "$rc" = "0" ]; then echo "Data has been loaded successfully."; touch /data/.preload_completed; else echo "Failed to load data."; fi; exit $rc; else echo "Skip loading data."; exit 0; fi']
        volumeMounts:
          - name:  {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}-tsdb-volume
            mountPath: /data
      {{- end }}
      containers:
      - name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}db
        image: "{{ include "image.repo" $ }}{{ $.Values.tsDb.image }}:{{ $.Values.tsDb.tag }}"
        {{- if $.Values.common.imagePullPolicy }}
        imagePullPolicy: {{ $.Values.common.imagePullPolicy }}
        {{- end }}
        resources:
{{ toYaml $.Values.tsDb.resources | indent 12 }}
        env:
        - name: "LICENSE"
          value: {{ $.Values.license | quote }}
        - name: "SEARCH_ENGINE"
          value: {{ $.Values.common.searchEngine }}
        {{- if $.Values.common.timezone }}
        - name: "TZ"
          value: {{ $.Values.common.timezone | quote }}
        {{- end }}
        securityContext:
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            runAsUser: 0
            privileged: false
            capabilities:
              drop:
              - all
              add:
              - CHOWN
              - DAC_OVERRIDE
              - FOWNER
              - FSETID
              - KILL
              - SETGID
              - SETUID
              - SETPCAP
              - NET_BIND_SERVICE
              - NET_RAW
              - SYS_CHROOT
              - MKNOD
              - AUDIT_WRITE
              - SETFCAP
              - SYS_RESOURCE
              - IPC_OWNER
              - SYS_NICE
        ports:
        - containerPort: 50000
          name: dbport50000
          protocol: TCP
        - containerPort: 50001
          name: dbport50001
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 50000
          initialDelaySeconds: 600
          timeoutSeconds: 300
        readinessProbe:
          tcpSocket:
            port: 50000
        {{- if or ($.Values.tsDb.persistence.enabled) ($.Values.tsDb.userScripts.enabled) }}
        volumeMounts:
        {{- end }}
        {{- if $.Values.tsDb.persistence.enabled }}
          - name:  {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}-tsdb-volume
            mountPath: /home/db2inst1/db2inst1
        {{- end }}
        {{- if and (not $.Values.global.sofySandboxContext) ($.Values.tsDb.userScripts.enabled) }}
          - name:  user-scripts
            mountPath: /SETUP/user_scripts
        {{- end }}
        {{- if and $.Values.global.sofySandboxContext $.Values.tsDb.demoPack.enabled }}
          - name:  demopack
            mountPath: /SETUP/user_scripts
        {{- end }}
{{- end }}
---
{{- end }}
{{- end }}
