{{- $envTypeList := splitList "," (nospace .Values.common.environmentType) -}}
{{- if has "share" $envTypeList }}
######################################################
# Licensed Materials - Property of HCL Technologies
#  HCL Commerce
#  (C) Copyright HCL Technologies Limited 1996, 2020
######################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: HCL-Commerce
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "-" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
  name: {{ .Values.common.tenant }}{{ .Values.common.environmentName}}{{.Values.toolingWeb.name}}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      chart: {{ .Chart.Name }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      component: {{ .Values.common.tenant }}{{ .Values.common.environmentName}}{{.Values.toolingWeb.name}}
      group: {{ .Values.common.tenant }}{{ .Values.common.environmentName}}
  replicas: {{ .Values.toolingWeb.replica }}
  template:
    metadata:
      annotations:
        productName: "HCL Commerce"
        productVersion: {{ .Values.common.productVersion | quote }}
      labels:
        app: HCL-Commerce
        chart: {{ .Chart.Name }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        component: {{ .Values.common.tenant }}{{ .Values.common.environmentName}}{{.Values.toolingWeb.name}}
        group: {{ .Values.common.tenant }}{{ .Values.common.environmentName}}
        app.kubernetes.io/name: {{ include "name" $ }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
    spec:
      {{- if .Values.toolingWeb.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.toolingWeb.nodeSelector | indent 8 }}
      {{- end }}
      affinity:
        nodeAffinity:
           {{- if .Values.toolingWeb.nodeLabel }}
           requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: wc-node-select-flag
                  operator: In
                  values:
                  - {{ .Values.toolingWeb.nodeLabel }}
           {{- else }}
           requiredDuringSchedulingIgnoredDuringExecution:
           {{- include "nodeAffinityRequiredDuringScheduling" . | indent 8 }}
           {{- end }}
           preferredDuringSchedulingIgnoredDuringExecution:
           {{- include "nodeAffinityPreferredDuringScheduling" . | indent 8 }}
      {{- include "toolingweb-podAntiAffinity" . | indent 6 }}
      hostNetwork: false
      hostPID: false
      hostIPC: false
      serviceAccountName: {{ .Values.common.serviceAccountName | default (printf "%s-commerce" .Release.Name) }}
      securityContext:
        fsGroup: 1000
      {{- if $.Values.vaultconsul.enabled }}
      initContainers:
      - name: vault-dependence-check
        image: "{{ include "image.repo" $ }}{{ $.Values.supportC.image }}:{{ $.Values.supportC.tag }}"
        tty: true
        {{- if $.Values.common.imagePullPolicy }}
        imagePullPolicy: {{ $.Values.common.imagePullPolicy }}
        {{- end }}
        args: ['depcheck', '-component','vault','-namespace',{{ $.Release.Namespace }},'-interval_time','10','-expect_during_time','120','-timeout','5']
      {{- end }}
      volumes:
        - name: logs-sharing
          emptyDir: {}
      {{- if .Values.common.bindingConfigMap }}
        - name: config-volume
          configMap:
            name: {{ .Values.common.bindingConfigMap }}
      {{- end }}
      {{- if include "image.pull.secret" . }}
      imagePullSecrets:
        - name: {{ include "image.pull.secret" . }}
      {{- end }}
      containers:
      - name: tooling-web
        image: "{{ include "image.repo" . }}{{ .Values.toolingWeb.image }}:{{ .Values.toolingWeb.tag }}"
        {{- if .Values.common.imagePullPolicy }}
        imagePullPolicy: {{ .Values.common.imagePullPolicy }}
        {{- end }}
        resources:
{{ toYaml .Values.toolingWeb.resources | indent 12 }}
        env:
        - name: "LICENSE"
          value: {{ .Values.license | quote }}
        {{- if $.Values.global.sofySolutionContext }}
        - name: "EXTERNAL_DOMAIN_NAME"
        {{- if $.Values.global.domain }}
          value: {{ $.Values.global.domain }}
        {{- else }}
          valueFrom:
              configMapKeyRef:
                name: {{ $.Release.Name }}-domain
                key: HOST
        {{- end }}
        - name: "AUTH_SEARCH_QUERY_BASE_URL"
          value: "https://commerce-preview.$(EXTERNAL_DOMAIN_NAME)"
        - name: "LIVE_SEARCH_QUERY_BASE_URL"
          value: ""
        - name: "SEARCH_DATA_QUERY_BASE_URL"
          value: "https://commerce-data-query.$(EXTERNAL_DOMAIN_NAME)"
        - name: "AUTH_REACT_STORE_BASE_URL"
          value: "https://commerce-preview.$(EXTERNAL_DOMAIN_NAME)"
        - name: "LIVE_REACT_STORE_BASE_URL"
          value: ""
        - name: "REACT_STORE_PREVIEW_BASE_URL"
          value: "https://commerce-preview-store.$(EXTERNAL_DOMAIN_NAME)"
        - name: "APPROVAL_BASE_URL"
          value: "https://commerce-preview.$(EXTERNAL_DOMAIN_NAME)"
        - name: "AUTH_TRANSACTION_BASE_URL"
          value: "https://commerce-preview.$(EXTERNAL_DOMAIN_NAME)"
        - name: "LIVE_TRANSACTION_BASE_URL"
          value: ""
        {{- else }} # not sofy
        - name: "EXTERNAL_DOMAIN_NAME"
          value: "{{ trimPrefix "." $.Values.common.externalDomain }}"
        {{- end }}
        {{- if eq $.Values.common.searchEngine "elastic" }}
        - name: "ELASTICSEARCH_ENABLED"
          value: "true"
        {{- end }}
        {{- if $.Values.storeWeb.enabled }}
        - name: "REACT_STORE_ENABLED"
          value: "true"
        {{- end }}
        {{- if $.Values.approvalApp.enabled }}
        - name: "APPROVAL_ENABLED"
          value: "true"
        {{- end }}
        {{- if $.Values.common.timezone }}
        - name: "TZ"
          value: {{ $.Values.common.timezone | quote }}
        {{- end }}
        - name: "EXTRA_CSP_SOURCE"
          value: {{ .Values.toolingWeb.extraCspSource | quote }}
        - name: "CONFIGURE_MODE"
          value: {{ .Values.common.configureMode | quote }}
        - name: "ENVIRONMENT"
          value: {{ .Values.common.environmentName | quote }}
        - name: "TENANT"
          value: {{ .Values.common.tenant | quote }}
        - name: "ENVTYPE"
          value: "share"
        {{- if $.Values.logging.jsonLogging.enabled }}
        - name: "ENABLE_JSON_LOGGING"
          value: "true"
        {{- end }}
        - name: "DOMAIN_NAME"
          value: "{{ .Release.Namespace }}.svc.cluster.local"
        {{- if $.Values.orchestrationApp.enabled }}
        - name: "ORCHESTRATION_ENABLED"
          value: "true"
        {{- end }}
        - name: "VAULT_CA"
          value: {{ .Values.vaultCA.enabled | quote }}
        {{- if (or (eq .Values.common.configureMode "Vault") .Values.vaultCA.enabled) }}
        - name: "VAULT_URL"
          value: {{ .Values.common.vaultUrl | quote  }}
        {{- if .Values.common.vaultTokenSecret }}
        - name: "VAULT_TOKEN"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.common.vaultTokenSecret }}
              key: VAULT_TOKEN
        {{- end }}
        {{- end }}
{{- if .Values.toolingWeb.envParameters }}
     {{- range $key, $value := .Values.toolingWeb.envParameters }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
     {{- end }}
{{- end }}
        ports:
        - containerPort: 7443
          name: port7443
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /tooling
            port: 7443
            scheme: HTTPS
          initialDelaySeconds: 240
          timeoutSeconds: 30
        readinessProbe:
          httpGet:
            path: /tooling/
            port: 7443
            scheme: HTTPS
        securityContext:
            {{- if $.Values.common.runAsNonRoot.enabled }}
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            {{- else }}
            allowPrivilegeEscalation: true
            runAsNonRoot: false
            runAsUser: 0
            {{- end }}
            readOnlyRootFilesystem: false
            privileged: false
            capabilities:
              drop:
              - all
              add:
              - CHOWN
              - DAC_OVERRIDE
              - FOWNER
              - FSETID
              - KILL
              - SETGID
              - SETUID
              - SETPCAP
              - NET_BIND_SERVICE
              - NET_RAW
              - SYS_CHROOT
              - MKNOD
              - AUDIT_WRITE
              - SETFCAP
        volumeMounts:
          - name: logs-sharing
            mountPath: /opt/WebSphere/HTTPServer/logs/container
        {{- if .Values.common.bindingConfigMap }}
          - name: config-volume
            mountPath: /SETUP/ext-config/config.properties
            subPath: config.properties
            readOnly: false
        {{- end }}
{{- end }}
