{{- if and .Values.ingress.enabled (ne .Values.ingress.ingressController "ambassador") (ne .Values.ingress.ingressController "emissary") (.Values.openshiftDeployment.enabled) }}
{{- $envTypeList := splitList "," (nospace .Values.common.environmentType) -}}
{{- if has "share" $envTypeList }}
{{- $ingress_conf := $.Values.ingress.tooling }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}tooling-route
  namespace: {{ $.Release.Namespace }}
  labels:
    app: HCL-Commerce
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "-" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    group: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}
spec:
  host: {{ tpl ($ingress_conf.domain | toString) $ }}
  path: /tooling
  to:
    kind: Service
    name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}{{ $.Values.toolingWeb.name }}
  port:
    targetPort: 7443
  tls:
    termination: reencrypt
    destinationCACertificate: |-
{{ $.Values.openshiftDeployment.destinationCACertificate | indent 6 }}
---
{{- if $.Values.approvalApp.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}tooling-approval-route
  namespace: {{ $.Release.Namespace }}
  labels:
    app: HCL-Commerce
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "-" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    group: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}
spec:
  host: {{ tpl ($ingress_conf.domain | toString) $ }}
  path: /approvals
  to:
    kind: Service
    name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName }}approval-app
  port:
    targetPort: 6643
  tls:
    termination: reencrypt
    destinationCACertificate: |-
{{ $.Values.openshiftDeployment.destinationCACertificate | indent 6 }}
{{- end }}
{{- end }}
{{- end }}
---
