{{- $envTypeList := splitList "," (nospace .Values.common.environmentType) }}
{{- range $envType := $envTypeList }}
{{- if ne $envType "share" }}
######################################################
# Licensed Materials - Property of HCL Technologies
#  HCL Commerce
#  (C) Copyright HCL Technologies Limited 1996, 2020
######################################################
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}{{$.Values.tsWeb.name}}
  labels:
    app: HCL-Commerce
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "-" }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
    component: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}{{$.Values.tsWeb.name}}
    app.kubernetes.io/name: {{ include "name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    {{- if $.Values.common.localStoreEnabled }}
    cloud.google.com/app-protocols: '{"https-web443":"HTTPS","https-cmc8000":"HTTPS","https-acc8001":"HTTPS","https-admin8002":"HTTPS","https-org8004":"HTTPS","https-pre8006":"HTTPS","https-was9043":"HTTPS"}'
    {{- else }}
    cloud.google.com/app-protocols: '{"https-cmc8000":"HTTPS","https-acc8001":"HTTPS","https-admin8002":"HTTPS","https-org8004":"HTTPS","https-pre8006":"HTTPS","https-was9043":"HTTPS"}'
    {{- end }}
spec:
  type: NodePort
  ports:
  {{- if $.Values.common.localStoreEnabled }}
  - port: 443
    name: https-web443
  {{- end }}
  - port: 8000
    name: https-cmc8000
  - port: 8001
    name: https-acc8001
  - port: 8002
    name: https-admin8002
  - port: 8004
    name: https-org8004
  - port: 8006
    name: https-pre8006
  {{- if $.Values.tsApp.wasAdminConsole.enabled }}
  - port: 9043
    name: https-was9043
  {{- end }}
  selector:
    component: {{ $.Values.common.tenant }}{{ $.Values.common.environmentName}}{{ $envType }}{{$.Values.tsWeb.name}}
{{- end }}
---
{{- end }}